/**
 * @module sage/schemes/elliptic_curves/ell_torsion
 * @description Torsion subgroups of elliptic curves over number fields (including Q)
 *
 * Port of: sage/schemes/elliptic_curves/ell_torsion.py
 *
 * This module provides functionality for computing torsion subgroups of elliptic
 * curves over number fields. The main class is EllipticCurveTorsionSubgroup which
 * represents the torsion subgroup of an elliptic curve.
 *
 * For finite fields, the torsion subgroup is the entire group of points on the curve.
 * For number fields (including Q), the torsion subgroup is computed using PARI/GP
 * or by computing p-primary parts using division polynomials.
 *
 * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py
 */

import { NotImplementedError, ValueError } from '../../errors.js';
import { type IntegerLike, toBigInt } from '../../types/coercion.js';
import { EllipticCurveGeneric } from './ell_generic.js';
import { EllipticCurvePoint, type FieldElement } from './ell_point.js';

/**
 * The torsion subgroup of an elliptic curve over a number field.
 *
 * This class represents the torsion subgroup of an elliptic curve E over a
 * number field K (including Q). It computes generators and structure of the
 * torsion subgroup.
 *
 * For finite fields, the entire group is torsion, so this class represents
 * the group of all rational points on the curve.
 *
 * @example
 * ```typescript
 * const E = EllipticCurve(GF(7n), [1n, 1n]);
 * const T = new EllipticCurveTorsionSubgroup(E);
 * console.log(T.order());     // e.g., 13n
 * console.log(T.ngens());     // 1 or 2
 * console.log(T.points());    // all torsion points
 * ```
 *
 * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup
 */
export class EllipticCurveTorsionSubgroup<F extends FieldElement = FieldElement> {
  private _E: EllipticCurveGeneric<F>;
  private _structure: bigint[];
  private _gens: EllipticCurvePoint<F>[];
  private _order: bigint;
  private _points: EllipticCurvePoint<F>[] | null = null;

  /**
   * Construct the torsion subgroup of an elliptic curve.
   *
   * @param E - An elliptic curve defined over a field
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.__init__
   */
  constructor(E: EllipticCurveGeneric<F>) {
    this._E = E;
    this._structure = [];
    this._gens = [];
    this._order = 1n;

    const K = E.base_ring;
    const p = K.characteristic;

    // For finite fields, compute the group structure using point enumeration
    // or baby-step giant-step methods
    if (p > 0n) {
      this._compute_finite_field_torsion();
    } else {
      // For characteristic 0 (number fields), would use PARI's elltors
      // For now, throw not implemented
      throw new NotImplementedError(
        'Torsion subgroup computation over number fields requires PARI/GP elltors'
      );
    }
  }

  /**
   * Compute the torsion subgroup for curves over finite fields.
   *
   * For finite fields, all points have finite order, so the torsion subgroup
   * is the entire group of points on the curve.
   */
  private _compute_finite_field_torsion(): void {
    // Get all points on the curve
    const allPoints = this._E.torsion_points();

    // The order is the number of points
    this._order = BigInt(allPoints.length);

    // For the structure, we need to find generators
    // The group E(F_q) is isomorphic to Z/n1Z x Z/n2Z where n2 | n1
    // (cyclic or product of two cyclic groups)

    if (allPoints.length <= 1) {
      // Only identity point
      this._structure = [];
      this._gens = [];
      return;
    }

    // Find generators using a simple algorithm:
    // 1. Find a point of maximum order (first generator)
    // 2. If that doesn't generate the whole group, find a second generator

    let maxOrderPoint = allPoints[1]!;
    let maxOrder = 1n;

    // Find point of maximum order
    for (const P of allPoints) {
      if (P.is_zero()) continue;
      const ord = this._compute_point_order(P, this._order);
      if (ord > maxOrder) {
        maxOrder = ord;
        maxOrderPoint = P;
      }
    }

    // Check if this point generates the whole group
    const generatedSet = new Set<string>();
    let Q = this._E.zero();
    for (let i = 0n; i < maxOrder; i++) {
      const key = Q.is_zero() ? 'O' : `${Q.x()},${Q.y()}`;
      generatedSet.add(key);
      Q = Q.add(maxOrderPoint);
    }

    if (BigInt(generatedSet.size) === this._order) {
      // Cyclic group
      this._structure = [maxOrder];
      this._gens = [maxOrderPoint];
    } else {
      // Need a second generator
      // The group is Z/n1Z x Z/n2Z where n1 * n2 = order and n2 | n1
      const n1 = maxOrder;
      const n2 = this._order / n1;

      // Find a point not in the subgroup generated by the first generator
      let secondGen: EllipticCurvePoint<F> | null = null;
      for (const P of allPoints) {
        const key = P.is_zero() ? 'O' : `${P.x()},${P.y()}`;
        if (!generatedSet.has(key)) {
          // Check if this point has order n2 modulo the first generator
          const ord = this._compute_point_order(P, n2);
          if (ord === n2) {
            secondGen = P;
            break;
          }
        }
      }

      if (secondGen) {
        this._structure = [n1, n2];
        this._gens = [maxOrderPoint, secondGen];
      } else {
        // Fallback: just use the first generator
        this._structure = [n1];
        this._gens = [maxOrderPoint];
      }
    }
  }

  /**
   * Compute the order of a point given a bound on the order.
   */
  private _compute_point_order(P: EllipticCurvePoint<F>, bound: bigint): bigint {
    if (P.is_zero()) return 1n;

    // The order divides the bound, so we can find it by dividing out factors
    let ord = bound;
    let Q = P.mul(ord);

    // Start with the bound and divide out prime factors
    for (const [prime, exp] of this._factor(bound)) {
      for (let i = 0n; i < exp; i++) {
        const newOrd = ord / prime;
        const R = P.mul(newOrd);
        if (R.is_zero()) {
          ord = newOrd;
        } else {
          break;
        }
      }
    }

    return ord;
  }

  /**
   * Simple trial division factorization.
   */
  private _factor(n: bigint): Array<[bigint, bigint]> {
    const factors: Array<[bigint, bigint]> = [];
    let remaining = n;

    if (remaining <= 1n) return factors;

    // Factor out 2
    if (remaining % 2n === 0n) {
      let exp = 0n;
      while (remaining % 2n === 0n) {
        exp++;
        remaining /= 2n;
      }
      factors.push([2n, exp]);
    }

    // Factor out odd primes
    let f = 3n;
    while (f * f <= remaining) {
      if (remaining % f === 0n) {
        let exp = 0n;
        while (remaining % f === 0n) {
          exp++;
          remaining /= f;
        }
        factors.push([f, exp]);
      }
      f += 2n;
    }

    if (remaining > 1n) {
      factors.push([remaining, 1n]);
    }

    return factors;
  }

  /**
   * Return the curve of this torsion subgroup.
   *
   * @returns The elliptic curve E
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.curve
   */
  curve(): EllipticCurveGeneric<F> {
    return this._E;
  }

  /**
   * Return a list of all the points in this torsion subgroup.
   *
   * The list is cached.
   *
   * @returns A list of all torsion points
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.points
   */
  points(): EllipticCurvePoint<F>[] {
    if (this._points !== null) {
      return this._points;
    }

    // Generate all points from the generators
    const points: EllipticCurvePoint<F>[] = [];
    const seen = new Set<string>();

    if (this._gens.length === 0) {
      // Only the identity
      this._points = [this._E.zero()];
      return this._points;
    }

    if (this._gens.length === 1) {
      // Cyclic case
      const gen = this._gens[0]!;
      const order = this._structure[0]!;
      let P = this._E.zero();
      for (let i = 0n; i < order; i++) {
        const key = P.is_zero() ? 'O' : `${P.x()},${P.y()}`;
        if (!seen.has(key)) {
          seen.add(key);
          points.push(P);
        }
        P = P.add(gen);
      }
    } else {
      // Two generators
      const gen1 = this._gens[0]!;
      const gen2 = this._gens[1]!;
      const order1 = this._structure[0]!;
      const order2 = this._structure[1]!;

      let P1 = this._E.zero();
      for (let i = 0n; i < order1; i++) {
        let P = P1;
        for (let j = 0n; j < order2; j++) {
          const key = P.is_zero() ? 'O' : `${P.x()},${P.y()}`;
          if (!seen.has(key)) {
            seen.add(key);
            points.push(P);
          }
          P = P.add(gen2);
        }
        P1 = P1.add(gen1);
      }
    }

    this._points = points;
    return points;
  }

  /**
   * Return the order (cardinality) of this torsion subgroup.
   *
   * @returns The number of elements in the torsion subgroup
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.order
   */
  order(): bigint {
    return this._order;
  }

  /**
   * Return the number of generators of this torsion subgroup.
   *
   * @returns The number of generators (0, 1, or 2)
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.ngens
   */
  ngens(): number {
    return this._gens.length;
  }

  /**
   * Return the i-th generator of this torsion subgroup.
   *
   * @param i - The index of the generator (0 or 1)
   * @returns The i-th generator point
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.gen
   */
  gen(i: number): EllipticCurvePoint<F> {
    if (i < 0 || i >= this._gens.length) {
      throw new ValueError(`Generator index ${i} out of range [0, ${this._gens.length})`);
    }
    return this._gens[i]!;
  }

  /**
   * Return the generators of this torsion subgroup.
   *
   * @returns A tuple of generator points
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.gens
   */
  gens(): EllipticCurvePoint<F>[] {
    return [...this._gens];
  }

  /**
   * Return the invariants of this torsion subgroup.
   *
   * The invariants are a tuple of positive integers (d1, d2, ...) where
   * d_i divides d_{i+1} and the group is isomorphic to Z/d1 x Z/d2 x ...
   *
   * For elliptic curves, there are at most 2 invariants.
   *
   * @returns The invariant factors
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.invariants
   */
  invariants(): bigint[] {
    return [...this._structure];
  }

  /**
   * Return a short name for this group structure.
   *
   * For example, "Z/4 + Z/2" for a group isomorphic to Z/4Z x Z/2Z.
   *
   * @returns A short string description
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.short_name
   */
  short_name(): string {
    if (this._structure.length === 0) {
      return 'Trivial group';
    }
    return this._structure.map((n) => `Z/${n}`).join(' + ');
  }

  /**
   * Compare two torsion groups by comparing the elliptic curves.
   *
   * @param other - Another torsion subgroup
   * @returns Comparison result (-1, 0, or 1)
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.__richcmp__
   */
  compare(other: EllipticCurveTorsionSubgroup<F>): number {
    const j1 = this._E.j_invariant();
    const j2 = other._E.j_invariant();

    if (j1.eq(j2)) {
      return 0;
    }

    // For ordering, compare string representations
    const s1 = j1.toString();
    const s2 = j2.toString();
    return s1 < s2 ? -1 : 1;
  }

  /**
   * Check if this torsion subgroup equals another.
   *
   * @param other - Another torsion subgroup
   * @returns True if equal
   */
  eq(other: EllipticCurveTorsionSubgroup<F>): boolean {
    return this.compare(other) === 0;
  }

  /**
   * Return the string representation of this torsion subgroup.
   *
   * @returns String representation
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup._repr_
   */
  toString(): string {
    return `Torsion Subgroup isomorphic to ${this.short_name()} associated to the ${this._E}`;
  }

  /**
   * Return an iterator over all elements of this torsion subgroup.
   *
   * @returns An iterator
   * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup.__iter__
   */
  *[Symbol.iterator](): Generator<EllipticCurvePoint<F>> {
    for (const P of this.points()) {
      yield P;
    }
  }

  /**
   * Return the number of elements in this torsion subgroup.
   *
   * @returns The order
   */
  get length(): number {
    return Number(this._order);
  }

  /**
   * Check if an element is in this torsion subgroup.
   *
   * @param P - A point
   * @returns True if P is in the torsion subgroup
   */
  contains(P: EllipticCurvePoint<F>): boolean {
    // For finite fields, all points are torsion
    // Just check if P is on the curve
    if (P.is_zero()) {
      return true;
    }

    try {
      const x = P.x();
      const y = P.y();
      return this._E.is_on_curve(x, y);
    } catch {
      return false;
    }
  }

  /**
   * Return the identity element (point at infinity).
   *
   * @returns The identity element
   */
  identity(): EllipticCurvePoint<F> {
    return this._E.zero();
  }

  /**
   * Return a random element of this torsion subgroup.
   *
   * @returns A random torsion point
   */
  random_element(): EllipticCurvePoint<F> {
    const pts = this.points();
    const idx = Math.floor(Math.random() * pts.length);
    return pts[idx]!;
  }
}

/**
 * Return an upper bound on the order of the torsion subgroup.
 *
 * An upper bound on the order of the torsion group of the elliptic curve
 * is obtained by counting points modulo several primes of good reduction.
 * Note that the upper bound returned by this function is a multiple of the
 * order of the torsion group, and in general will be greater than the order.
 *
 * @param E - An elliptic curve over Q or a number field
 * @param number_of_places - Positive integer (default: 20); the number of
 *                           places that will be used to find the bound
 * @returns An upper bound on the torsion order
 * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:torsion_bound
 */
export function torsion_bound<F extends FieldElement>(
  E: EllipticCurveGeneric<F>,
  number_of_places: number = 20
): bigint {
  const K = E.base_ring;
  const p = K.characteristic;

  // For finite fields, the torsion is just the group order
  if (p > 0n) {
    // Count points on the curve
    const torsion = new EllipticCurveTorsionSubgroup(E);
    return torsion.order();
  }

  // For number fields (characteristic 0), we count points modulo primes
  // This is a simplified implementation for Q
  throw new NotImplementedError(
    'torsion_bound for number fields not fully implemented - requires integral model and reduction'
  );
}

/**
 * Return the torsion order of an elliptic curve.
 *
 * This is faster than computing the full torsion subgroup when only the
 * order is needed.
 *
 * @param E - An elliptic curve
 * @returns The torsion order
 * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py (via ell_rational_field.py:torsion_order)
 */
export function torsion_order<F extends FieldElement>(E: EllipticCurveGeneric<F>): bigint {
  const torsion = new EllipticCurveTorsionSubgroup(E);
  return torsion.order();
}

/**
 * Return the torsion points of an elliptic curve.
 *
 * @param E - An elliptic curve
 * @returns A list of all torsion points
 * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py (via torsion_subgroup().points())
 */
export function torsion_points<F extends FieldElement>(
  E: EllipticCurveGeneric<F>
): EllipticCurvePoint<F>[] {
  const torsion = new EllipticCurveTorsionSubgroup(E);
  return torsion.points();
}

/**
 * Return the torsion subgroup of an elliptic curve.
 *
 * @param E - An elliptic curve over a field
 * @returns The torsion subgroup
 * @see Reference: sage/schemes/elliptic_curves/ell_torsion.py:EllipticCurveTorsionSubgroup
 */
export function torsion_subgroup<F extends FieldElement>(
  E: EllipticCurveGeneric<F>
): EllipticCurveTorsionSubgroup<F> {
  return new EllipticCurveTorsionSubgroup(E);
}

/**
 * Compute a basis for the p-primary part of the torsion subgroup.
 *
 * The p-primary part consists of all points whose order is a power of p.
 * This function finds a basis (generators) for this subgroup.
 *
 * @param E - An elliptic curve
 * @param p - A prime number
 * @param m - Maximum power of p to consider (default: derived from torsion bound)
 * @returns A list of pairs [generator, order_exponent] where order_exponent
 *          is the exponent e such that p^e is the order of the generator
 * @see Reference: sage/schemes/elliptic_curves/ell_generic.py:_p_primary_torsion_basis
 */
export function _p_primary_torsion_basis<F extends FieldElement>(
  E: EllipticCurveGeneric<F>,
  p: bigint | number,
  m?: bigint | number
): Array<[EllipticCurvePoint<F>, number]> {
  const pVal = typeof p === 'number' ? BigInt(p) : p;

  // Get all torsion points
  const allPoints = E.torsion_points();

  // Find points whose order is a power of p
  const pPrimary: Array<[EllipticCurvePoint<F>, number]> = [];

  // Find the maximum exponent in the p-primary part
  let maxExp = m !== undefined ? Number(m) : 10; // Default max exponent

  // Track the structure of the p-primary part
  const pPowers: bigint[] = [];
  let power = pVal;
  for (let e = 1; e <= maxExp; e++) {
    pPowers.push(power);
    power *= pVal;
  }

  // Find points of order p^e for each e
  const pointsByOrder = new Map<number, EllipticCurvePoint<F>[]>();

  for (const P of allPoints) {
    if (P.is_zero()) continue;

    // Compute the order of P
    let ord = 1n;
    let Q = P;
    for (let i = 0n; i < BigInt(allPoints.length); i++) {
      ord++;
      Q = Q.add(P);
      if (Q.is_zero()) break;
    }

    // Check if the order is a power of p
    let tempOrd = ord;
    let exp = 0;
    while (tempOrd % pVal === 0n) {
      tempOrd /= pVal;
      exp++;
    }

    if (tempOrd === 1n && exp > 0) {
      // Order is p^exp
      if (!pointsByOrder.has(exp)) {
        pointsByOrder.set(exp, []);
      }
      pointsByOrder.get(exp)!.push(P);
    }
  }

  // Build the basis
  // The p-primary part is Z/p^{e1} x Z/p^{e2} where e2 <= e1
  const exponents = Array.from(pointsByOrder.keys()).sort((a, b) => b - a);

  if (exponents.length === 0) {
    return [];
  }

  // First generator: highest order
  const highestExp = exponents[0]!;
  const firstGen = pointsByOrder.get(highestExp)![0]!;
  pPrimary.push([firstGen, highestExp]);

  // Check if we need a second generator
  const generatedCount = BigInt(pPowers[highestExp - 1]!);
  if (generatedCount < BigInt(allPoints.length)) {
    // Need a second generator
    // Find a point not in the subgroup generated by the first generator
    const generatedSet = new Set<string>();
    let Q = E.zero();
    for (let i = 0n; i <= generatedCount; i++) {
      const key = Q.is_zero() ? 'O' : `${Q.x()},${Q.y()}`;
      generatedSet.add(key);
      Q = Q.add(firstGen);
    }

    for (const [exp, points] of pointsByOrder) {
      for (const P of points) {
        const key = P.is_zero() ? 'O' : `${P.x()},${P.y()}`;
        if (!generatedSet.has(key)) {
          pPrimary.push([P, exp]);
          return pPrimary;
        }
      }
    }
  }

  return pPrimary;
}

/**
 * Check if a point has finite order.
 *
 * @param P - A point on an elliptic curve
 * @returns True if P has finite order
 * @see Reference: sage/schemes/elliptic_curves/ell_point.py:has_finite_order
 */
export function has_finite_order<F extends FieldElement>(P: EllipticCurvePoint<F>): boolean {
  // The identity point always has finite order (order 1)
  if (P.is_zero()) {
    return true;
  }

  // For finite fields, all points have finite order
  const char = P.curve.base_ring.characteristic;
  if (char > 0n) {
    return true;
  }

  // For number fields, checking if a point has finite order is harder
  // Would require height pairing or other methods
  // For now, return false for non-finite fields (conservative)
  return false;
}

/**
 * Check if a point has infinite order.
 *
 * @param P - A point on an elliptic curve
 * @returns True if P has infinite order
 * @see Reference: sage/schemes/elliptic_curves/ell_point.py:has_infinite_order
 */
export function has_infinite_order<F extends FieldElement>(P: EllipticCurvePoint<F>): boolean {
  return !has_finite_order(P);
}

/**
 * Return the order of a point on an elliptic curve.
 *
 * For points on curves over finite fields, the order is always finite.
 * For points on curves over number fields, the order may be infinite.
 *
 * @param P - A point on an elliptic curve
 * @returns The order of P (may be 'Infinity' for infinite order)
 * @see Reference: sage/schemes/elliptic_curves/ell_point.py:order
 */
export function point_order<F extends FieldElement>(P: EllipticCurvePoint<F>): bigint | 'Infinity' {
  if (P.is_zero()) {
    return 1n;
  }

  const char = P.curve.base_ring.characteristic;

  // For finite fields, compute the order
  if (char > 0n) {
    // Use the order method on the point if available
    const ord = P.order();
    if (ord !== undefined) {
      return ord;
    }

    // Otherwise compute by brute force (only for small fields)
    let Q = P;
    let n = 1n;
    const maxIter = char * char; // Upper bound from Hasse

    while (!Q.is_zero() && n < maxIter) {
      Q = Q.add(P);
      n++;
    }

    return Q.is_zero() ? n : 'Infinity';
  }

  // For number fields, would need more sophisticated methods
  return 'Infinity';
}

/**
 * Compute the order of a point given a multiple of the order.
 *
 * This is more efficient than computing the order from scratch when
 * we know that mP = O for some m.
 *
 * @param P - A point on an elliptic curve
 * @param m - A positive integer such that mP = O
 * @param factorization - Optional factorization of m
 * @returns The exact order of P
 * @see Reference: sage/groups/generic.py:order_from_multiple
 */
export function order_from_multiple<F extends FieldElement>(
  P: EllipticCurvePoint<F>,
  m: IntegerLike,
  factorization?: Array<[bigint, number]>
): bigint {
  const mBig = toBigInt(m);
  if (P.is_zero()) {
    return 1n;
  }

  // Verify that mBig*P = O
  const mP = P.mul(mBig);
  if (!mP.is_zero()) {
    throw new ValueError(`${mBig}*P is not the identity`);
  }

  // Compute factorization if not provided
  const factors = factorization ?? _factor_bigint(mBig);

  // Start with mBig and divide out prime factors
  let ord = mBig;

  for (const [prime, exp] of factors) {
    const primeB = BigInt(prime);
    for (let i = 0; i < exp; i++) {
      const newOrd = ord / primeB;
      const Q = P.mul(newOrd);
      if (Q.is_zero()) {
        ord = newOrd;
      } else {
        break;
      }
    }
  }

  return ord;
}

/**
 * Simple trial division factorization.
 */
function _factor_bigint(n: bigint): Array<[bigint, number]> {
  const factors: Array<[bigint, number]> = [];
  let remaining = n;

  if (remaining <= 1n) return factors;

  // Factor out 2
  if (remaining % 2n === 0n) {
    let exp = 0;
    while (remaining % 2n === 0n) {
      exp++;
      remaining /= 2n;
    }
    factors.push([2n, exp]);
  }

  // Factor out odd primes
  let f = 3n;
  while (f * f <= remaining) {
    if (remaining % f === 0n) {
      let exp = 0;
      while (remaining % f === 0n) {
        exp++;
        remaining /= f;
      }
      factors.push([f, exp]);
    }
    f += 2n;
  }

  if (remaining > 1n) {
    factors.push([remaining, 1]);
  }

  return factors;
}

/**
 * Compute the discrete logarithm of Q with respect to P.
 *
 * Given points P and Q on an elliptic curve, find n such that Q = nP,
 * or raise an error if no such n exists.
 *
 * Uses the baby-step giant-step algorithm for efficiency.
 *
 * @param Q - A point on an elliptic curve
 * @param P - A point on the same elliptic curve
 * @param ord - Optional order of P
 * @param operation - The operation (default '+', used for compatibility)
 * @returns n such that Q = nP
 * @see Reference: sage/groups/generic.py:discrete_log
 */
export function discrete_log<F extends FieldElement>(
  Q: EllipticCurvePoint<F>,
  P: EllipticCurvePoint<F>,
  ord?: IntegerLike,
  _operation?: string
): bigint {
  const ordBig = ord !== undefined ? toBigInt(ord) : undefined;
  // Handle trivial cases
  if (Q.is_zero()) {
    return 0n;
  }

  if (P.is_zero()) {
    throw new ValueError('discrete_log: base point is identity');
  }

  if (Q.eq(P)) {
    return 1n;
  }

  // Get the order of P
  const order = ordBig ?? point_order(P);
  if (order === 'Infinity') {
    throw new ValueError('discrete_log: base point has infinite order');
  }

  // Baby-step giant-step algorithm
  const m = _isqrt(order) + 1n;

  // Baby steps: compute P, 2P, ..., mP
  const babySteps = new Map<string, bigint>();
  let R = P.curve.zero();
  for (let j = 0n; j < m; j++) {
    const key = R.is_zero() ? 'O' : `${R.x()},${R.y()}`;
    if (!babySteps.has(key)) {
      babySteps.set(key, j);
    }
    R = R.add(P);
  }

  // Giant steps: compute Q - i*m*P for i = 0, 1, ...
  const mP = P.mul(m);
  const negMP = mP.neg();
  let G = Q;

  for (let i = 0n; i <= m + 1n; i++) {
    const key = G.is_zero() ? 'O' : `${G.x()},${G.y()}`;
    if (babySteps.has(key)) {
      const j = babySteps.get(key)!;
      const result = (i * m + j) % order;
      return result;
    }
    G = G.add(negMP);
  }

  throw new ValueError('discrete_log: Q is not in the subgroup generated by P');
}

/**
 * Integer square root.
 */
function _isqrt(n: bigint): bigint {
  if (n < 0n) throw new ValueError('Square root of negative number');
  if (n < 2n) return n;

  let x = n;
  let y = (x + 1n) / 2n;

  while (y < x) {
    x = y;
    y = (x + n / x) / 2n;
  }

  return x;
}
