export interface NativeResult {
  regressionId?: string;
  function: string; args: string[]; seed: number;
  result: string | null; error: string | null; errorType: string | null;
}
export interface NativeSuccess extends NativeResult { result: string; error: null; errorType: null }
interface NativeFixtureTypes {
  "./lll.fixtures.json": NativeResult;
  "./lll_dpe.fixtures.json": NativeResult;
  "./lll_gso.fixtures.json": NativeResult;
  "./lll_real.fixtures.json": NativeResult;
  "./lll_wrapper.fixtures.json": NativeResult;
  "./real_matrix.fixtures.json": NativeResult;
  "./modular_linear.fixtures.json": NativeResult;
  "./qr.fixtures.json": NativeResult;
  "./matrix_products.fixtures.json": NativeResult;

  "./lll_dependents.native.json.gz": NativeResult;
  "./ideal_adapters.native.json": NativeResult;
  "./newton_sums.native.json.gz": NativeResult;
  "./bounded_recombination.native.json.gz": NativeResult;
  "./field_predicates.native.json.gz": NativeSuccess;
  "./lll_norms.native.json.gz": NativeResult;
  "./rational_polynomials.native.json.gz": NativeResult;
  "./factor_lll_progress.native.json": NativeResult;
  "./integer_factorization.native.json.gz": NativeSuccess;
  "./factor_bounds.native.json.gz": NativeResult;
  "./general_hnf.native.json.gz": NativeSuccess;
  "./gen2_ffelt.native.json.gz": NativeSuccess;
  "./algdep_lll.native.json": NativeResult;
  "./hnf_permutation.native.json.gz": NativeResult;
  "./prime_matrices.native.json.gz": NativeResult;
  "./lll_norms.bounded.native.json": NativeSuccess;
  "./division_points_order.native.json": NativeSuccess;
  "./weierstrass_morphism_roots.native.json": NativeSuccess;
  "./ell_generic_coordinate_roots.native.json.gz": NativeSuccess;
  "./ell_generic_isomorphism_order.native.json.gz": NativeSuccess;
  "./lll_reduction.native.json": NativeResult;
  "./ideal_classes.native.json": NativeResult;
  "./number_field_automorphism_order.native.json": NativeSuccess;
  "./factorization.native.json.gz": NativeResult;
  "./valuation.native.json": NativeResult;
  "./trace_base.native.json": NativeResult;
  "./conjugate_bound.native.json.gz": NativeSuccess;
  "./number_field_factorization.native.json": NativeSuccess;
  "./trace_norm.native.json": NativeResult;
  "./pari_nf_factor.native.json": NativeSuccess;
  "./prime_valuation.native.json": NativeSuccess;
  "./polynomial_distinct_roots.native.json": NativeSuccess;
  "./polynomial_roots.native.json": NativeSuccess;
  "./polynomial_factor_state.native.json": NativeSuccess;
  "./finite_polynomial_roots.native.json": NativeSuccess;
  "./finite_polynomial_roots_state.native.json": NativeSuccess;
  "./polynomial_factor_dispatch.native.json": NativeSuccess;
  "./extension_is_square.native.json": NativeSuccess;
  "./integer_mod_roots.native.json.gz": NativeSuccess;
  "./integer_mod_root_helpers.native.json": NativeSuccess;
  "./extension_square_root.native.json.gz": NativeSuccess;
  "./ZZXFactoring_traces.native.json.gz": NativeResult;
  "./ZZXFactoring_hensel_state.native.json.gz": NativeSuccess;
  "./ZZXFactoring_cold_recombination.native.json.gz": NativeSuccess;
  "./ZZXFactoring_cardinality.native.json.gz": NativeSuccess;
  "./ZZ_pX_context.native.json.gz": NativeSuccess;
  "./LLL.native.json.gz": NativeResult;
  "./FFT_primes.native.json.gz": NativeSuccess;
  "./ZZXFactoring_recovery.native.json.gz": NativeResult;
  "./ZZXFactoring_selection.native.json.gz": NativeResult;
  "./lzz_pX_minpoly.native.json.gz": NativeResult;
  "./lzz_pX_projection.native.json.gz": NativeResult;
  "./ZZ_pX_zero_modulus.native.json.gz": NativeSuccess;
  "./lzz_pX_context.native.json.gz": NativeSuccess;
  "./lzz_pX_word_factor_recovery.native.json.gz": NativeResult;
  "./lzz_pX_element_minpoly.native.json.gz": NativeResult;
  "./lzz_pX_multiplier_fallback.native.json.gz": NativeSuccess;
  "./ZZXFactoring_gauss.native.json.gz": NativeResult;
  "./lzz_pX_xgcd.native.json.gz": NativeSuccess;
  "./ZZ_prime_generation.native.json.gz": NativeSuccess;
  "./mat_ZZ_crt.native.json.gz": NativeResult;
  "./ZZXFactoring_lift.native.json.gz": NativeResult;
  "./ZZX1_product_state.native.json.gz": NativeSuccess;
  "./lzz_pXFactoring.native.json.gz": NativeResult;
  "./ZZX_gcd_state.native.json.gz": NativeSuccess;
  "./ZZXFactoring_got_them.native.json.gz": NativeResult;
  "./ZZ_pX_quotient.native.json.gz": NativeResult;
  "./ZZ_random_stream.native.json.gz": NativeResult;
  "./lzz_pX_fft_context.native.json.gz": NativeResult;
  "./lzz_pX_root_prerequisites.native.json.gz": NativeResult;
  "./ZZXFactoring_small_primes.native.json.gz": NativeSuccess;
  "./ZZX_factor_driver.native.json.gz": NativeSuccess;
  "./lzz_pX_quotient.native.json.gz": NativeResult;
  "./lzz_pX_word_context.native.json.gz": NativeResult;
  "./ZZ_prime_sequence.native.json.gz": NativeSuccess;
  "./ZZ_pX_state.native.json.gz": NativeSuccess;
  "./lzz_pX_zero_modulus.native.json.gz": NativeSuccess;
  "./lzz_pX_rebuild.native.json.gz": NativeSuccess;
  "./lzz_pX_projection_rebuild.native.json.gz": NativeSuccess;
  "./mat_lzz_p_linear.native.json.gz": NativeResult;
  "./lzz_pX1.native.json.gz": NativeResult;
  "./ZZX1_division.native.json.gz": NativeSuccess;
  "./ZZ_random_sampling.native.json.gz": NativeSuccess;
  "./ZZXFactoring_local_info.native.json.gz": NativeSuccess;
  "./mat_ZZ_reconstruction.native.json.gz": NativeResult;
  "./mat_lzz_p.native.json.gz": NativeResult;
  "./ZZXFactoring_cold_prime.native.json.gz": NativeSuccess;
  "./modular-root-dispatch.native.json": NativeSuccess;
}
export function nativeFixtures<F extends keyof NativeFixtureTypes>(testURL: string, formerFixture: F): Promise<NativeFixtureTypes[F][]>;
export function nativeInputs(name: string, seed?: number, runs?: number): { module: string; regressionId?: string; cases: { function: string; rows: [number, ...(number | string | (number | string)[])[]][] }[] }[];

export function legacyNativeFixtures(testURL: string, suiteID: keyof NativeFixtureTypes): Promise<{
  probe: number; function: string; kind: string; group: string;
  args: (number | string | string[])[]; expected?: unknown; result?: string;
  error?: string; errorType?: string;
}[]>;
