/**
 * # Introduction to Lattices
 *
 * Lattices are the foundation of post-quantum cryptography. Unlike elliptic
 * curve cryptography, lattice problems remain hard even for quantum computers
 * (as far as we know). This makes lattices crucial for the future of security.
 *
 * ## What is a Lattice?
 *
 * A lattice is a discrete additive subgroup of R^n. Think of it as an
 * infinite grid of points in space, generated by integer combinations
 * of basis vectors.
 *
 * ## Why Lattices Matter for Cryptography
 *
 * 1. POST-QUANTUM: Resistant to Shor's algorithm
 * 2. VERSATILE: Enables FHE, signatures, encryption, ZK proofs
 * 3. EFFICIENT: Often faster than elliptic curves
 * 4. STANDARDIZED: NIST PQC standards use lattices (Kyber, Dilithium)
 *
 * @module tutorial/part6-advanced/18-lattices-intro/lattice-basics
 */

import { IntegerLattice, IntegerMatrixFromEntries, lllReduce, gramSchmidt } from 'sagemath-ts';

console.log("=== Introduction to Lattices ===\n");

// ============================================================================
// Section 1: Definition and Basic Concepts
// ============================================================================

console.log("--- Section 1: What is a Lattice? ---\n");

/**
 * DEFINITION
 *
 * A lattice L is a discrete subgroup of R^n that is generated by
 * integer linear combinations of a finite set of basis vectors.
 *
 * Given basis vectors b_1, b_2, ..., b_d in R^n:
 *   L = {a_1*b_1 + a_2*b_2 + ... + a_d*b_d : a_i in Z}
 *
 * The vectors b_i form a BASIS for L.
 * The number d is the RANK of the lattice.
 * The lattice lives in R^n where n is the DIMENSION.
 *
 * FULL-RANK: When d = n (most common in crypto)
 *
 * EXAMPLE: The simplest lattice Z^2
 *   Basis: b_1 = (1, 0), b_2 = (0, 1)
 *   Lattice points: all (a, b) with integer a, b
 *
 * EXAMPLE: A skewed lattice
 *   Basis: b_1 = (1, 0), b_2 = (0.5, 0.866)
 *   Still has "grid" structure but rotated/skewed
 */

console.log("Definition:");
console.log("  L = {a_1*b_1 + ... + a_d*b_d : a_i in Z}");
console.log("  b_1, ..., b_d are the basis vectors\n");

// Create a simple 2D lattice
const basis2D = IntegerMatrixFromEntries([
  [1n, 0n],
  [0n, 1n]
]);

console.log("Example: Standard lattice Z^2");
console.log("  Basis: (1, 0) and (0, 1)");
console.log("  Points: all integer pairs (a, b)\n");

// A more interesting lattice
const skewedBasis = IntegerMatrixFromEntries([
  [2n, 1n],
  [0n, 3n]
]);

console.log("Example: A non-trivial lattice");
console.log("  Basis:");
console.log("    b_1 = (2, 1)");
console.log("    b_2 = (0, 3)");

// Create the lattice
const L = IntegerLattice(skewedBasis, { lllReduce: false });
console.log(`  Rank: ${L.rank()}`);
console.log(`  Degree (ambient dimension): ${L.degree()}\n`);

// ============================================================================
// Section 2: Basis and Determinant
// ============================================================================

console.log("--- Section 2: Basis and Determinant ---\n");

/**
 * BASIS NON-UNIQUENESS
 *
 * A lattice has INFINITELY many bases!
 *
 * Any unimodular transformation (matrix with det = +/- 1)
 * gives a new valid basis for the same lattice.
 *
 * Example: Z^2 has many bases:
 *   Standard: {(1,0), (0,1)}
 *   Rotated:  {(1,1), (1,-1)} (same lattice!)
 *   Skewed:   {(1,0), (1,1)}  (same lattice!)
 *
 * KEY INSIGHT: Some bases are "better" than others:
 * - Short vectors are useful (LLL reduction finds them)
 * - Nearly orthogonal is useful (easier to solve problems)
 *
 * DETERMINANT (Volume)
 *
 * The determinant of a lattice is invariant under basis change:
 *   det(L) = |det(B)| for any basis matrix B
 *
 * Geometric interpretation:
 *   det(L) = volume of the fundamental parallelepiped
 *          = "density" of lattice points
 *
 * For a full-rank lattice in R^n:
 *   det(L) = sqrt(det(B * B^T))
 *
 * Smaller det(L) means denser lattice (more points per unit volume).
 */

console.log("Bases are NOT unique!");
console.log("  Same lattice, different bases:");
console.log("  {(1,0), (0,1)} and {(1,1), (1,-1)} generate same Z^2\n");

console.log("Determinant (lattice volume):");
console.log("  det(L) = |det(B)| = volume of fundamental region");
console.log("  Invariant under basis change!\n");

// Calculate determinant for our lattice
const basisMatrix = L.basisMatrix();
console.log("Our lattice:");
console.log(`  Basis matrix B =`);
for (let i = 0; i < basisMatrix.nrows; i++) {
  const row = [];
  for (let j = 0; j < basisMatrix.ncols; j++) {
    row.push(basisMatrix.get(i, j).value);
  }
  console.log(`    [${row.join(', ')}]`);
}

// For 2x2, det = ad - bc
const a = basisMatrix.get(0, 0).value;
const b = basisMatrix.get(0, 1).value;
const c = basisMatrix.get(1, 0).value;
const d = basisMatrix.get(1, 1).value;
const det = a * d - b * c;
console.log(`  det(L) = |${a}*${d} - ${b}*${c}| = ${det < 0n ? -det : det}\n`);

// ============================================================================
// Section 3: Gram-Schmidt and Orthogonality
// ============================================================================

console.log("--- Section 3: Gram-Schmidt Orthogonalization ---\n");

/**
 * GRAM-SCHMIDT ORTHOGONALIZATION
 *
 * Given a basis B = (b_1, ..., b_d), produce an orthogonal basis
 * B* = (b_1*, ..., b_d*):
 *
 *   b_1* = b_1
 *   b_i* = b_i - sum_{j<i} mu_{i,j} * b_j*
 *
 * where mu_{i,j} = <b_i, b_j*> / <b_j*, b_j*>
 *
 * The mu coefficients measure "how non-orthogonal" the basis is.
 * For an orthogonal basis: all mu_{i,j} = 0 for i != j.
 *
 * IMPORTANCE FOR CRYPTOGRAPHY:
 *
 * The Gram-Schmidt vectors tell us about:
 * 1. How "good" a basis is (orthogonal = good)
 * 2. Lower bound on shortest vector: min_i ||b_i*||
 * 3. Quality of LLL reduction
 *
 * HADAMARD RATIO:
 *
 * H(B) = (det(L) / (prod_i ||b_i||))^{1/n}
 *
 * Range: 0 < H(B) <= 1
 * H(B) = 1 iff basis is orthogonal
 * Higher H(B) = better basis
 */

console.log("Gram-Schmidt Orthogonalization:");
console.log("  Transform basis B into orthogonal basis B*");
console.log("  b_i* = b_i - sum_{j<i} mu_{i,j} * b_j*\n");

// Compute Gram-Schmidt for our lattice
const gsResult = gramSchmidt(skewedBasis);
console.log("Our lattice Gram-Schmidt:");
console.log("  Original basis:");
console.log(`    b_1 = (${skewedBasis.get(0, 0).value}, ${skewedBasis.get(0, 1).value})`);
console.log(`    b_2 = (${skewedBasis.get(1, 0).value}, ${skewedBasis.get(1, 1).value})`);

console.log("  Orthogonalized basis:");
console.log(`    b_1* = (${gsResult.orthogonalBasis[0]![0]!.toFixed(3)}, ${gsResult.orthogonalBasis[0]![1]!.toFixed(3)})`);
console.log(`    b_2* = (${gsResult.orthogonalBasis[1]![0]!.toFixed(3)}, ${gsResult.orthogonalBasis[1]![1]!.toFixed(3)})`);

console.log("  Gram-Schmidt norms:");
console.log(`    ||b_1*||^2 = ${gsResult.B[0]!.toFixed(3)}`);
console.log(`    ||b_2*||^2 = ${gsResult.B[1]!.toFixed(3)}`);

console.log("  mu coefficients:");
console.log(`    mu_{2,1} = ${gsResult.mu[1]![0]!.toFixed(3)}\n`);

// ============================================================================
// Section 4: Shortest Vectors and Minima
// ============================================================================

console.log("--- Section 4: Shortest Vectors ---\n");

/**
 * SUCCESSIVE MINIMA
 *
 * The i-th minimum lambda_i(L) is the smallest r such that
 * L contains i linearly independent vectors of length <= r.
 *
 * lambda_1(L): length of shortest nonzero vector
 * lambda_2(L): length such that we have 2 independent short vectors
 * ...
 *
 * MINKOWSKI'S BOUND:
 *
 * For a full-rank lattice in R^n:
 *   lambda_1(L) <= sqrt(n) * det(L)^{1/n}
 *
 * This gives an UPPER BOUND on the shortest vector length.
 * In practice, the shortest vector is often much shorter.
 *
 * GAUSSIAN HEURISTIC:
 *
 * For a "random" lattice, we expect:
 *   lambda_1(L) ~ sqrt(n / (2*pi*e)) * det(L)^{1/n}
 *
 * This is used to estimate lattice problem hardness.
 *
 * FINDING SHORT VECTORS:
 *
 * Finding the exact shortest vector (SVP) is NP-hard under
 * randomized reductions. But we CAN find:
 * - Approximately shortest: LLL finds 2^{n/2} approximation
 * - Better approximations: BKZ, enumeration, sieving
 */

console.log("Successive Minima:");
console.log("  lambda_1(L): shortest nonzero vector length");
console.log("  lambda_i(L): i-th shortest independent vector\n");

console.log("Minkowski's Bound:");
console.log("  lambda_1 <= sqrt(n) * det(L)^{1/n}\n");

console.log("Gaussian Heuristic (typical lattice):");
console.log("  lambda_1 ~ sqrt(n / (2*pi*e)) * det(L)^{1/n}");
console.log("  Used to estimate security of lattice schemes\n");

// Example calculation
const n = 2;
const detVal = Number(det < 0n ? -det : det);
const minkowski = Math.sqrt(n) * Math.pow(detVal, 1/n);
const gaussian = Math.sqrt(n / (2 * Math.PI * Math.E)) * Math.pow(detVal, 1/n);

console.log(`For our lattice (n=${n}, det=${detVal}):`);
console.log(`  Minkowski bound: ${minkowski.toFixed(3)}`);
console.log(`  Gaussian heuristic: ${gaussian.toFixed(3)}\n`);

// ============================================================================
// Section 5: Dual Lattice
// ============================================================================

console.log("--- Section 5: Dual Lattice ---\n");

/**
 * DUAL LATTICE
 *
 * The dual lattice L* of L is:
 *   L* = {v in R^n : <v, u> in Z for all u in L}
 *
 * Properties:
 * - (L*)* = L (double dual is original)
 * - det(L*) = 1 / det(L)
 * - If B is a basis for L, then (B^{-1})^T is a basis for L*
 *
 * For full-rank lattices:
 *   L* = {v : <v, b_i> in Z for all basis vectors b_i}
 *
 * IMPORTANCE IN CRYPTOGRAPHY:
 *
 * Many lattice problems have "dual" versions:
 * - SIS (Short Integer Solution) uses primal
 * - LWE (Learning With Errors) uses dual
 *
 * The dual lattice appears in:
 * - Regev's encryption scheme
 * - Lattice-based signatures
 * - Security reductions
 */

console.log("Dual Lattice L*:");
console.log("  L* = {v : <v, u> in Z for all u in L}\n");

console.log("Properties:");
console.log("  (L*)* = L");
console.log("  det(L*) = 1 / det(L)");
console.log("  If B generates L, then (B^{-1})^T generates L*\n");

console.log("Cryptographic significance:");
console.log("  SIS problem: find short v with A*v = 0 (primal)");
console.log("  LWE problem: find s from noisy inner products (dual)\n");

// ============================================================================
// Section 6: Computational Problems
// ============================================================================

console.log("--- Section 6: Hard Lattice Problems ---\n");

/**
 * HARD LATTICE PROBLEMS
 *
 * These problems are believed hard even for quantum computers!
 *
 * SVP (Shortest Vector Problem):
 *   Given a lattice L, find a shortest nonzero vector.
 *   - Exact SVP: NP-hard under randomized reductions
 *   - gamma-SVP: Find vector within factor gamma of shortest
 *
 * CVP (Closest Vector Problem):
 *   Given a lattice L and target t, find lattice point closest to t.
 *   - At least as hard as SVP
 *   - gamma-CVP: Find point within factor gamma of closest
 *
 * SIVP (Shortest Independent Vectors Problem):
 *   Find n linearly independent vectors, each short.
 *
 * GapSVP (Decision version):
 *   Distinguish lattices with lambda_1 <= 1 from lambda_1 > gamma.
 *
 * LWE (Learning With Errors):
 *   Given (A, b = A*s + e), find s.
 *   - As hard as worst-case lattice problems
 *   - Foundation of most lattice crypto
 *
 * SIS (Short Integer Solution):
 *   Given random A, find short s with A*s = 0.
 *   - Used in hash functions and signatures
 */

console.log("Hard Problems (believed quantum-resistant):\n");

console.log("SVP - Shortest Vector Problem:");
console.log("  Find the shortest nonzero vector in lattice");
console.log("  NP-hard to solve exactly\n");

console.log("CVP - Closest Vector Problem:");
console.log("  Given target t, find nearest lattice point");
console.log("  At least as hard as SVP\n");

console.log("LWE - Learning With Errors:");
console.log("  Find s from b = A*s + e (noisy equations)");
console.log("  Foundation of Kyber (NIST standard)\n");

console.log("SIS - Short Integer Solution:");
console.log("  Find short s with A*s = 0");
console.log("  Foundation of Dilithium signatures\n");

// ============================================================================
// Section 7: Simple Code Examples
// ============================================================================

console.log("--- Section 7: Working with Lattices ---\n");

// Create a 3D lattice
const basis3D = IntegerMatrixFromEntries([
  [1n, 0n, 3n],
  [0n, 2n, 1n],
  [0n, 2n, 7n]
]);

console.log("Creating a 3D lattice:");
console.log("  Basis vectors:");
console.log("    v1 = (1, 0, 3)");
console.log("    v2 = (0, 2, 1)");
console.log("    v3 = (0, 2, 7)\n");

const L3 = IntegerLattice(basis3D, { lllReduce: false });
console.log(`  Rank: ${L3.rank()}`);
console.log(`  Dimension: ${L3.degree()}`);

// Apply LLL reduction
console.log("\nApplying LLL reduction...");
const L3reduced = IntegerLattice(basis3D, { lllReduce: true });
const reducedBasis = L3reduced.reducedBasis;

console.log("  Reduced basis:");
for (let i = 0; i < reducedBasis.nrows; i++) {
  const row = [];
  for (let j = 0; j < reducedBasis.ncols; j++) {
    row.push(reducedBasis.get(i, j).value);
  }
  console.log(`    v${i+1}' = (${row.join(', ')})`);
}

// Compare vector lengths
console.log("\nVector length comparison:");
function vectorNorm(matrix: any, row: number): number {
  let sum = 0;
  for (let j = 0; j < matrix.ncols; j++) {
    const v = Number(matrix.get(row, j).value);
    sum += v * v;
  }
  return Math.sqrt(sum);
}

console.log("  Original first vector: ||v1|| = " + vectorNorm(basis3D, 0).toFixed(3));
console.log("  Reduced first vector:  ||v1'|| = " + vectorNorm(reducedBasis, 0).toFixed(3));
console.log("\nLLL finds shorter vectors!\n");

// ============================================================================
// Summary
// ============================================================================

console.log("=== Summary ===\n");

console.log("A lattice is a discrete grid in R^n:");
console.log("  L = {integer combinations of basis vectors}\n");

console.log("Key concepts:");
console.log("  - Basis: generators of the lattice (not unique)");
console.log("  - Determinant: volume, invariant under basis change");
console.log("  - Gram-Schmidt: measures basis quality");
console.log("  - Shortest vector: hard to find, easy to verify\n");

console.log("Hard problems (quantum-resistant):");
console.log("  - SVP: find shortest vector");
console.log("  - CVP: find closest point to target");
console.log("  - LWE/SIS: foundations of modern lattice crypto\n");

console.log("Next: SVP and CVP problems in detail");
