/**
 * @module matkermod.test
 * @description Tests for linear algebra over Z/dZ (Howell form).
 *
 * Golden values are taken verbatim from PARI's own regression suite
 * `reference/pari/src/test/in/bbhnf` + `reference/pari/src/test/32/bbhnf`
 * and from the documentation examples in
 * `reference/pari/src/functions/linear_algebra/{matkermod,matimagemod,matdetmod}`.
 *
 * NOTE: the `matdetmod` doc example claims `matdetmod([4,2,3;4,5,6;7,8,9],27) == 9`,
 * but the actual determinant is -9, i.e. 18 mod 27, and PARI's own test output
 * (`test/32/bbhnf`, line 240) records 18. We assert 18 (PARI's real behaviour).
 */

import { describe, expect, it } from 'bun:test';
import {
  matdetmod,
  matimagemod,
  matinvmod,
  matkermod,
  matkermod_basis,
  PariDomainError,
  PariInvError,
  zm_from_rows,
  zm_to_rows,
  type ZM,
} from './matkermod.js';

const R = (rows: number[][]): ZM => zm_from_rows(rows.map((r) => r.map(BigInt)));
const rowsOf = (A: ZM): number[][] => zm_to_rows(A).map((r) => r.map(Number));

/* deterministic PRNG so the tests are reproducible */
function mkrnd(s: bigint): (n: number) => number {
  let seed = s;
  return (n: number) => {
    seed = (seed * 6364136223846793005n + 1442695040888963407n) & ((1n << 64n) - 1n);
    return Number((seed >> 33n) % BigInt(n));
  };
}

function randMat(rnd: (n: number) => number, m: number, k: number, n: bigint): bigint[][] {
  const rows: bigint[][] = [];
  for (let i = 0; i < m; i++)
    rows.push(Array.from({ length: k }, () => BigInt(rnd(Number(n)))));
  return rows;
}

/** all vectors v in (Z/n)^k with rows*v == 0 */
function bruteKernel(rows: bigint[][], n: bigint): Set<string> {
  const k = rows.length === 0 ? 0 : rows[0]!.length;
  const N = Number(n);
  const out = new Set<string>();
  const v = new Array<number>(k).fill(0);
  const rec = (i: number): void => {
    if (i === k) {
      for (const r of rows) {
        let s = 0n;
        for (let j = 0; j < k; j++) s += r[j]! * BigInt(v[j]!);
        if (((s % n) + n) % n !== 0n) return;
      }
      out.add(v.join(','));
      return;
    }
    for (let t = 0; t < N; t++) {
      v[i] = t;
      rec(i + 1);
    }
  };
  rec(0);
  return out;
}

/** the Z/n-submodule generated by the columns of `cols` (ambient dimension k) */
function span(cols: ZM, n: bigint, k: number): Set<string> {
  const N = Number(n);
  const out = new Set<string>();
  const c = cols.length;
  const coef = new Array<number>(c).fill(0);
  const rec = (i: number): void => {
    if (i === c) {
      const v = new Array<bigint>(k).fill(0n);
      for (let j = 0; j < c; j++)
        for (let t = 0; t < k; t++) v[t] = (v[t]! + BigInt(coef[j]!) * cols[j]![t]!) % n;
      out.add(v.map((x) => Number(((x % n) + n) % n)).join(','));
      return;
    }
    for (let t = 0; t < N; t++) {
      coef[i] = t;
      rec(i + 1);
    }
  };
  rec(0);
  return out;
}

function exactDet(rows: bigint[][]): bigint {
  const n = rows.length;
  if (n === 0) return 1n;
  if (n === 1) return rows[0]![0]!;
  let s = 0n;
  for (let j = 0; j < n; j++) {
    const sub = rows.slice(1).map((r) => r.filter((_, k) => k !== j));
    s += (j % 2 === 0 ? 1n : -1n) * rows[0]![j]! * exactDet(sub);
  }
  return s;
}

describe('matkermod: PARI test/in/bbhnf golden values (d = 6)', () => {
  // 24 calls from reference/pari/src/test/in/bbhnf lines 86-109,
  // expected output decoded from reference/pari/src/test/32/bbhnf lines 26-107.
  const cases: Array<[number[][], number[][]]> = [
    [[[0]], [[1]]],
    [[[1]], []],
    [[[2]], [[3]]],
    [[[1], [0]], []],
    [[[2], [0]], [[3]]],
    [[[0], [0]], [[1]]],
    [[[3], [0]], [[2]]],
    [[[0], [1]], []],
    [[[0], [2]], [[3]]],
    [[[1], [3]], []],
    [[[2], [3]], []],
    [[[2], [4]], [[3]]],
    [[[1, 0]], [[0], [1]]],
    [[[0, 1]], [[1], [0]]],
    [
      [[2, 0]],
      [
        [3, 0],
        [0, 1],
      ],
    ],
    [[[1, 3]], [[3], [1]]],
    [
      [[0, 3]],
      [
        [1, 0],
        [0, 2],
      ],
    ],
    [
      [[2, 3]],
      [
        [3, 0],
        [0, 2],
      ],
    ],
    [
      [
        [1, 0],
        [0, 0],
      ],
      [[0], [1]],
    ],
    [
      [
        [2, 0],
        [0, 3],
      ],
      [
        [3, 0],
        [0, 2],
      ],
    ],
    [
      [
        [1, 1],
        [0, 1],
      ],
      [],
    ],
    [
      [
        [2, 1],
        [0, 3],
      ],
      [
        [3, 2],
        [0, 2],
      ],
    ],
    [
      [
        [4, 2],
        [4, 2],
      ],
      [
        [3, 1],
        [0, 1],
      ],
    ],
    [
      [
        [2, 2],
        [3, 0],
      ],
      [[2], [1]],
    ],
  ];

  for (const [A, K] of cases) {
    it(`matkermod(${JSON.stringify(A)}, 6)`, () => {
      expect(rowsOf(matkermod(R(A), 6n).ker)).toEqual(K);
    });
  }
});

describe('matkermod / matimagemod: documentation examples', () => {
  it('matkermod([1,2,3;5,1,4], 6)', () => {
    // reference/pari/src/functions/linear_algebra/matkermod
    const A = R([
      [1, 2, 3],
      [5, 1, 4],
    ]);
    expect(rowsOf(matkermod(A, 6n).ker)).toEqual([
      [2, 1],
      [2, 1],
      [0, 3],
    ]);
  });

  it('matimagemod([2,1;0,2], 6, &U)', () => {
    // reference/pari/src/functions/linear_algebra/matimagemod
    const A = R([
      [2, 1],
      [0, 2],
    ]);
    const { im, U } = matimagemod(A, 6n, true);
    expect(rowsOf(im)).toEqual([
      [1, 0],
      [0, 2],
    ]);
    expect(rowsOf(U!)).toEqual([
      [5, 1],
      [3, 4],
    ]);
  });

  it('matimagemod([1;2], 4)', () => {
    expect(rowsOf(matimagemod(R([[1], [2]]), 4n).im)).toEqual([
      [2, 1],
      [0, 2],
    ]);
  });

  it('matimagemod([4,1;0,4], 8, &U)', () => {
    const { im, U } = matimagemod(
      R([
        [4, 1],
        [0, 4],
      ]),
      8n,
      true
    );
    expect(rowsOf(im)).toEqual([
      [2, 1],
      [0, 4],
    ]);
    expect(rowsOf(U!)).toEqual([
      [0, 0],
      [2, 1],
    ]);
  });

  it('matimagemod of PARI test matrices mod 1800', () => {
    // reference/pari/src/test/32/bbhnf lines 3-23
    const M1 = R([
      [900, 130, 117, 275, 85],
      [0, 4, 0, 0, 0],
      [0, 0, 9, 0, 0],
      [0, 0, 0, 25, 0],
      [0, 0, 0, 0, 10],
    ]);
    expect(rowsOf(matimagemod(M1, 1800n).im)).toEqual([
      [900, 130, 117, 275, 85],
      [0, 4, 0, 0, 0],
      [0, 0, 9, 0, 0],
      [0, 0, 0, 25, 0],
      [0, 0, 0, 0, 10],
    ]);
    const M2 = R([
      [11, 28, -1],
      [2, 1, 89],
      [5, 78, 15],
      [0, 8, 3],
      [0, 0, 3],
    ]);
    expect(rowsOf(matimagemod(M2, 1800n).im)).toEqual([
      [870, 11, 1603, 1016],
      [15, 2, 1, 8],
      [0, 5, 3, 0],
      [0, 0, 8, 3],
      [0, 0, 0, 3],
    ]);
  });

  it('matinvmod([3,1,2;1,2,1;3,1,1], 6)', () => {
    const U = matinvmod(
      R([
        [3, 1, 2],
        [1, 2, 1],
        [3, 1, 1],
      ]),
      6n
    );
    expect(rowsOf(U)).toEqual([
      [1, 1, 3],
      [2, 3, 5],
      [1, 0, 5],
    ]);
  });

  it('matdetmod values from PARI test/32/bbhnf', () => {
    expect(
      matdetmod(
        R([
          [4, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
        ]),
        27n
      )
    ).toBe(18n);
    expect(
      matdetmod(
        R([
          [0, 1],
          [1, 0],
        ]),
        9n
      )
    ).toBe(8n);
    expect(
      matdetmod(
        R([
          [7, 1],
          [1, 0],
        ]),
        9n
      )
    ).toBe(8n);
    expect(
      matdetmod(
        R([
          [6, 0],
          [0, 1],
        ]),
        9n
      )
    ).toBe(6n);
  });
});

describe('matkermod: composite moduli, verified by brute force', () => {
  it('every returned basis vector is in the kernel (n = 12,36,100,360)', () => {
    const rnd = mkrnd(12345n);
    let checked = 0;
    for (const n of [12n, 36n, 100n, 360n]) {
      for (let m = 1; m <= 4; m++)
        for (let k = 1; k <= 4; k++) {
          for (let c = 0; c < 25; c++) {
            const rows = randMat(rnd, m, k, n);
            const { ker } = matkermod(zm_from_rows(rows), n);
            for (const v of ker)
              for (const r of rows) {
                let s = 0n;
                for (let j = 0; j < k; j++) s += r[j]! * v[j]!;
                expect(((s % n) + n) % n).toBe(0n);
              }
            checked++;
          }
        }
    }
    expect(checked).toBe(1600);
  });

  it('the returned basis spans exactly the full kernel (exhaustive, small n)', () => {
    const rnd = mkrnd(777n);
    let checked = 0;
    for (const n of [4n, 6n, 8n, 9n, 12n]) {
      for (let m = 1; m <= 3; m++)
        for (let k = 1; k <= 3; k++) {
          for (let c = 0; c < 10; c++) {
            const rows = randMat(rnd, m, k, n);
            const { ker } = matkermod(zm_from_rows(rows), n);
            const brute = bruteKernel(rows, n);
            const sp = span(ker, n, k);
            expect(sp.size).toBe(brute.size);
            for (const s of sp) expect(brute.has(s)).toBe(true);
            checked++;
          }
        }
    }
    expect(checked).toBe(450);
  });

  it('matimagemod spans the same submodule as the columns of A, and A*U == H', () => {
    const rnd = mkrnd(31337n);
    for (const n of [4n, 6n, 12n]) {
      for (let m = 1; m <= 3; m++)
        for (let k = 1; k <= 3; k++)
          for (let c = 0; c < 8; c++) {
            const rows = randMat(rnd, m, k, n);
            const A = zm_from_rows(rows);
            const { im, U } = matimagemod(A, n, true);
            const s1 = span(A, n, m);
            const s2 = span(im, n, m);
            expect(s2.size).toBe(s1.size);
            for (const x of s2) expect(s1.has(x)).toBe(true);
            for (let j = 0; j < U!.length; j++)
              for (let i = 0; i < m; i++) {
                let s = 0n;
                for (let t = 0; t < k; t++) s += rows[i]![t]! * U![j]![t]!;
                expect(((s % n) + n) % n).toBe(((im[j]![i]! % n) + n) % n);
              }
          }
    }
  });

  it('matdetmod agrees with the exact determinant reduced mod d', () => {
    const rnd = mkrnd(999n);
    for (const d of [36n, 27n, 100n, 360n])
      for (let n = 1; n <= 4; n++)
        for (let c = 0; c < 25; c++) {
          const rows = randMat(rnd, n, n, 50n);
          expect(matdetmod(zm_from_rows(rows), d)).toBe(((exactDet(rows) % d) + d) % d);
        }
  });

  it('matinvmod returns a genuine left inverse whenever it succeeds', () => {
    const rnd = mkrnd(4242n);
    let inverted = 0;
    for (const d of [1800n, 31n, 36n])
      for (let m = 1; m <= 4; m++)
        for (let n2 = 1; n2 <= 4; n2++)
          for (let c = 0; c < 20; c++) {
            const rows = randMat(rnd, m, n2, d);
            let U: ZM;
            try {
              U = matinvmod(zm_from_rows(rows), d);
            } catch (e) {
              expect(e).toBeInstanceOf(PariInvError);
              continue;
            }
            inverted++;
            const Urows = zm_to_rows(U);
            for (let i = 0; i < Urows.length; i++)
              for (let j = 0; j < n2; j++) {
                let s = 0n;
                for (let t = 0; t < m; t++) s += Urows[i]![t]! * rows[t]![j]!;
                expect(((s % d) + d) % d).toBe(i === j ? 1n : 0n);
              }
          }
    expect(inverted).toBeGreaterThan(100);
  });
});

describe('matkermod: edge cases and errors', () => {
  it('d = 1 (zero ring) gives an empty matrix', () => {
    expect(
      matkermod(
        R([
          [1, 2],
          [3, 4],
        ]),
        1n
      ).ker
    ).toEqual([]);
    expect(
      matimagemod(
        R([
          [1, 2],
          [3, 4],
        ]),
        1n
      ).im
    ).toEqual([]);
    expect(matdetmod(R([[3]]), 1n)).toBe(0n);
  });

  it('d <= 0 is a domain error', () => {
    expect(() => matkermod(R([[1]]), 0n)).toThrow(PariDomainError);
    expect(() => matimagemod(R([[1]]), -1n)).toThrow(PariDomainError);
    expect(() => matdetmod(R([[1]]), 0n)).toThrow(PariDomainError);
  });

  it('matkermod also returns the image when asked', () => {
    const A = R([
      [1, 2, 3],
      [5, 1, 4],
    ]);
    const { ker, im } = matkermod(A, 6n, true);
    expect(rowsOf(ker)).toEqual([
      [2, 1],
      [2, 1],
      [0, 3],
    ]);
    expect(rowsOf(im!)).toEqual(rowsOf(matimagemod(A, 6n).im));
  });

  it('matkermod_basis returns kernel vectors as rows', () => {
    const basis = matkermod_basis(
      [
        [1n, 2n, 3n],
        [5n, 1n, 4n],
      ],
      6n
    );
    expect(basis).toEqual([
      [2n, 2n, 0n],
      [1n, 1n, 3n],
    ]);
  });

  it('tall matrices take the transposed-image shortcut and still agree', () => {
    // m > 2n triggers the `matimagemod(A^T)` pre-reduction in matkermod.
    const rnd = mkrnd(24680n);
    for (const n of [12n, 36n]) {
      for (let k = 1; k <= 2; k++) {
        for (let c = 0; c < 15; c++) {
          const rows = randMat(rnd, 5 * k, k, n);
          const { ker } = matkermod(zm_from_rows(rows), n);
          const brute = bruteKernel(rows, n);
          const sp = span(ker, n, k);
          expect(sp.size).toBe(brute.size);
          for (const s of sp) expect(brute.has(s)).toBe(true);
        }
      }
    }
  });
});
