/**
 * @module sage/rings/function_field/order
 * @description Orders of function fields
 *
 * Port of: sage/rings/function_field/order.py
 */

import { NotImplementedError } from '../../errors.js';
import type { ConstantFieldElement } from './constant_field.js';
import type { FunctionFieldElement } from './element.js';
import type { FunctionField } from './function_field.js';
import { IdealMonoid } from './ideal.js';
import type { FunctionFieldIdeal } from './ideal.js';

/**
 * Base class for orders in function fields.
 *
 * @see Reference: sage/rings/function_field/order.py:121 (FunctionFieldOrder_base)
 */
export abstract class FunctionFieldOrder_base<C extends ConstantFieldElement> {
  readonly _field: FunctionField<C>;

  constructor(field: FunctionField<C>) {
    this._field = field;
  }

  /** Return the fractional ideal generated by ``gens``. */
  abstract ideal(...gens: unknown[]): FunctionFieldIdeal<C>;

  /** Coerce ``f`` into an element of this order. */
  abstract __call__(f: unknown): FunctionFieldElement<C>;

  /** Return ``true`` if ``f`` lies in this order. */
  abstract contains(f: FunctionFieldElement<C>): boolean;

  abstract _repr_(): string;

  toString(): string {
    return this._repr_();
  }

  /**
   * Return ``false`` since orders are never fields.
   *
   * @see Reference: sage/rings/function_field/order.py:151 (is_field)
   */
  is_field(_proof: boolean = true): boolean {
    return false;
  }

  /**
   * Return ``true`` since orders in function fields are Noetherian.
   *
   * @see Reference: sage/rings/function_field/order.py:162 (is_noetherian)
   */
  is_noetherian(): boolean {
    return true;
  }

  /**
   * Return the function field to which the order belongs.
   *
   * @see Reference: sage/rings/function_field/order.py:173 (function_field)
   */
  function_field(): FunctionField<C> {
    return this._field;
  }

  /** Alias of {@link function_field}, as in SageMath. */
  fraction_field(): FunctionField<C> {
    return this._field;
  }

  /**
   * Return ``true`` if the order is a subring of ``other``.
   *
   * @see Reference: sage/rings/function_field/order.py:186 (is_subring)
   */
  is_subring(other: unknown): boolean {
    if (other === this._field) {
      return true;
    }
    throw new NotImplementedError(
      'SAGE_NOT_IMPLEMENTED: FunctionFieldOrder_base.is_subring for orders other than the field itself'
    );
  }

  /**
   * Return the monoid of ideals of the order.
   *
   * @see Reference: sage/rings/function_field/order.py:206 (ideal_monoid)
   */
  ideal_monoid(): IdealMonoid<C> {
    return new IdealMonoid(this);
  }
}

/**
 * Base class for orders in function fields.
 *
 * @see Reference: sage/rings/function_field/order.py:218 (FunctionFieldOrder)
 */
export abstract class FunctionFieldOrder<
  C extends ConstantFieldElement,
> extends FunctionFieldOrder_base<C> {
  _repr_(): string {
    return `Order in ${this._field}`;
  }
}

/**
 * Base class for infinite orders in function fields.
 *
 * @see Reference: sage/rings/function_field/order.py:234 (FunctionFieldOrderInfinite)
 */
export abstract class FunctionFieldOrderInfinite<
  C extends ConstantFieldElement,
> extends FunctionFieldOrder_base<C> {
  _repr_(): string {
    return `Infinite order in ${this.function_field()}`;
  }
}

/**
 * Base class of maximal orders of function fields.
 *
 * @see Reference: sage/rings/function_field/order.py:248 (FunctionFieldMaximalOrder)
 */
export abstract class FunctionFieldMaximalOrder<
  C extends ConstantFieldElement,
> extends FunctionFieldOrder<C> {
  override _repr_(): string {
    return `Maximal order of ${this.function_field()}`;
  }
}

/**
 * Base class of maximal infinite orders of function fields.
 *
 * SageMath makes this a subclass of both {@link FunctionFieldMaximalOrder} and
 * `FunctionFieldOrderInfinite`; TypeScript has no multiple inheritance, so we
 * extend `FunctionFieldOrderInfinite` (the class that carries the behaviour
 * relevant to `FunctionFieldPlace._richcmp_`) and override `_repr_`.
 *
 * @see Reference: sage/rings/function_field/order.py:264 (FunctionFieldMaximalOrderInfinite)
 * @see Deviation: function-field maximal infinite order inheritance
 */
export abstract class FunctionFieldMaximalOrderInfinite<
  C extends ConstantFieldElement,
> extends FunctionFieldOrderInfinite<C> {
  override _repr_(): string {
    return `Maximal infinite order of ${this.function_field()}`;
  }
}
