/**
 * @module sage/rings/function_field/order_rational
 * @description Orders of function fields: rational
 *
 * Port of: sage/rings/function_field/order_rational.py
 */

import { NotImplementedError } from '../../errors.js';
import type { Polynomial } from '../polynomial/polynomial_element.js';
import type { PolynomialRing } from '../polynomial/polynomial_ring.js';
import type { ConstantField, ConstantFieldElement } from './constant_field.js';
import type { FunctionFieldElement_rational } from './element_rational.js';
import type { RationalFunctionField } from './function_field_rational.js';
import type { FunctionFieldIdeal } from './ideal.js';
import {
  FunctionFieldIdealInfinite_rational,
  FunctionFieldIdeal_rational,
} from './ideal_rational.js';
import { FunctionFieldMaximalOrder, FunctionFieldMaximalOrderInfinite } from './order.js';

/** `lcm` of a nonempty list of polynomials over a field. */
function polynomial_lcm<C extends ConstantFieldElement>(
  polys: Array<Polynomial<C>>
): Polynomial<C> {
  let l = polys[0]!;
  for (let i = 1; i < polys.length; i++) {
    const b = polys[i]!;
    const g = l.gcd(b);
    l = l.mul(b).quo_rem(g)[0];
  }
  return l;
}

/** `gcd` of a nonempty list of polynomials over a field. */
function polynomial_gcd<C extends ConstantFieldElement>(
  polys: Array<Polynomial<C>>
): Polynomial<C> {
  let g = polys[0]!;
  for (let i = 1; i < polys.length; i++) {
    g = g.gcd(polys[i]!);
  }
  return g;
}

/**
 * Maximal orders of rational function fields.
 *
 * @see Reference: sage/rings/function_field/order_rational.py:31 (FunctionFieldMaximalOrder_rational)
 */
export class FunctionFieldMaximalOrder_rational<
  C extends ConstantFieldElement,
> extends FunctionFieldMaximalOrder<C> {
  readonly _ring: PolynomialRing<C>;
  private readonly _gen_: FunctionFieldElement_rational<C>;
  private readonly _basis_: Array<FunctionFieldElement_rational<C>>;

  constructor(field: RationalFunctionField<C>) {
    super(field);
    this._ring = field._ring;
    this._gen_ = this.__call__(this._ring.gen());
    this._basis_ = [field.one()];
  }

  override function_field(): RationalFunctionField<C> {
    return this._field as RationalFunctionField<C>;
  }

  override fraction_field(): RationalFunctionField<C> {
    return this._field as RationalFunctionField<C>;
  }

  /**
   * Make ``f`` a function field element of this order.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:65 (_element_constructor_)
   */
  override __call__(f: unknown): FunctionFieldElement_rational<C> {
    const F = this.function_field();
    let e: FunctionFieldElement_rational<C>;
    try {
      e = F.__call__(f);
    } catch {
      throw new TypeError(`unable to convert to an element of ${F}`);
    }
    if (e.denominator().degree() !== 0) {
      throw new TypeError(`${e} is not an element of ${this}`);
    }
    return e;
  }

  /**
   * Return ``true`` if ``f`` lies in this order, i.e. its denominator is a
   * constant.
   */
  override contains(f: FunctionFieldElement_rational<C>): boolean {
    return f.denominator().degree() === 0;
  }

  /**
   * Return the basis of the order as a module over the polynomial ring: `(1,)`.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:346 (basis)
   */
  basis(): Array<FunctionFieldElement_rational<C>> {
    return this._basis_;
  }

  /**
   * @see Reference: sage/rings/function_field/order_rational.py:361 (gen)
   */
  gen(n: number = 0): FunctionFieldElement_rational<C> {
    if (n !== 0) {
      throw new RangeError('there is only one generator');
    }
    return this._gen_;
  }

  /**
   * @see Reference: sage/rings/function_field/order_rational.py:384 (ngens)
   */
  ngens(): number {
    return 1;
  }

  /**
   * Return the fractional ideal generated by ``gens``.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:397 (ideal)
   */
  override ideal(...args: unknown[]): FunctionFieldIdeal_rational<C> {
    const K = this.function_field();
    let raw: unknown[];
    if (args.length === 1) {
      const a = args[0];
      if (Array.isArray(a)) {
        raw = a;
      } else if (a instanceof FunctionFieldIdeal_rational) {
        raw = a.gens();
      } else {
        raw = [a];
      }
    } else {
      raw = args;
    }

    const gens = raw.map((e) => K.__call__(e)).filter((e) => !e.is_zero());

    let gen: FunctionFieldElement_rational<C>;
    if (gens.length === 0) {
      gen = K.zero();
    } else {
      const d = polynomial_lcm(gens.map((c) => c.denominator())).monic();
      const g = polynomial_gcd(gens.map((c) => K.__call__(d).mul(c).numerator())).monic();
      gen = K.__call__(g).div(K.__call__(d));
    }
    return new FunctionFieldIdeal_rational(this, gen);
  }

  /**
   * Return the fractional ideal with generators ``gens``.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:93 (ideal_with_gens_over_base)
   */
  ideal_with_gens_over_base(gens: unknown[]): FunctionFieldIdeal_rational<C> {
    return this.ideal(gens);
  }

  /**
   * Return a field isomorphic to the residue field at the prime ideal.
   *
   * The residue field is by definition `k[x]/q` where `q` is the irreducible
   * polynomial generating the prime ideal and `k` is the constant base field.
   *
   * Only places of degree one are supported: for those the residue field is
   * the constant field itself, which is what SageMath's `_residue_field_global`
   * (`order_rational.py:240`) and its number-field branch both produce.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:112 (_residue_field)
   */
  _residue_field(
    ideal: FunctionFieldIdeal<C>,
    _name?: string
  ): [ConstantField<C>, (e: C) => FunctionFieldElement_rational<C>, (f: Polynomial<C>) => C] {
    const F = this.function_field();
    const K = F.constant_base_field();

    const q = (ideal as FunctionFieldIdeal_rational<C>).gen().numerator();

    if (q.degree() !== 1) {
      throw new NotImplementedError(
        'SAGE_NOT_IMPLEMENTED: FunctionFieldMaximalOrder_rational._residue_field for places ' +
          `of degree ${q.degree()} > 1 (SageMath's _residue_field_global builds ` +
          'k.extension(deg q) and a root of q in it)'
      );
    }

    const from_R = (e: C): FunctionFieldElement_rational<C> => F.__call__(e);
    const to_R = (f: Polynomial<C>): C => {
      const r = f.mod(q);
      return r.isZero() ? K.zero() : r.getCoeff(0);
    };
    return [K, from_R, to_R];
  }

  /**
   * Return a finite field isomorphic to the residue field at ``q``.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:240 (_residue_field_global)
   */
  _residue_field_global(_q: Polynomial<C>, _name?: string): never {
    throw new NotImplementedError(
      'SAGE_NOT_IMPLEMENTED: FunctionFieldMaximalOrder_rational._residue_field_global ' +
        '(residue fields of places of degree > 1)'
    );
  }
}

/**
 * Maximal infinite orders of rational function fields.
 *
 * @see Reference: sage/rings/function_field/order_rational.py:439 (FunctionFieldMaximalOrderInfinite_rational)
 */
export class FunctionFieldMaximalOrderInfinite_rational<
  C extends ConstantFieldElement,
> extends FunctionFieldMaximalOrderInfinite<C> {
  constructor(field: RationalFunctionField<C>) {
    super(field);
  }

  override function_field(): RationalFunctionField<C> {
    return this._field as RationalFunctionField<C>;
  }

  override fraction_field(): RationalFunctionField<C> {
    return this._field as RationalFunctionField<C>;
  }

  /**
   * Make ``f`` an element of this order.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:472 (_element_constructor_)
   */
  override __call__(f: unknown): FunctionFieldElement_rational<C> {
    const F = this.function_field();
    let e: FunctionFieldElement_rational<C>;
    try {
      e = F.__call__(f);
    } catch {
      throw new TypeError(`unable to convert to an element of ${F}`);
    }
    if (e.denominator().degree() < e.numerator().degree()) {
      throw new TypeError(`${e} is not an element of ${this}`);
    }
    return e;
  }

  override contains(f: FunctionFieldElement_rational<C>): boolean {
    return f.denominator().degree() >= f.numerator().degree();
  }

  /**
   * @see Reference: sage/rings/function_field/order_rational.py:500 (basis)
   */
  basis(): Array<FunctionFieldElement_rational<C>> {
    return [this.function_field().one()];
  }

  /**
   * Return the unique prime ideal of the order.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:518 (prime_ideal)
   */
  prime_ideal(): FunctionFieldIdealInfinite_rational<C> {
    return this.ideal(this.function_field().gen().inv());
  }

  /**
   * Return the fractional ideal generated by ``gens``.
   *
   * @see Reference: sage/rings/function_field/order_rational.py:532 (ideal)
   */
  override ideal(...args: unknown[]): FunctionFieldIdealInfinite_rational<C> {
    const K = this.function_field();
    let raw: unknown[];
    if (args.length === 1) {
      const a = args[0];
      if (Array.isArray(a)) {
        raw = a;
      } else if (a instanceof FunctionFieldIdealInfinite_rational) {
        raw = a.gens();
      } else {
        raw = [a];
      }
    } else {
      raw = args;
    }

    const gens = raw.map((g) => K.__call__(g));
    const nonzero = gens.filter((g) => !g.is_zero());

    let gen: FunctionFieldElement_rational<C>;
    if (nonzero.length === 0) {
      gen = K.zero();
    } else {
      let d = Number.NEGATIVE_INFINITY;
      for (const g of nonzero) {
        d = Math.max(d, g.numerator().degree() - g.denominator().degree());
      }
      gen = K.gen().pow(d);
    }
    return new FunctionFieldIdealInfinite_rational(this, gen);
  }
}
