/**
 * Tests for Gröbner basis computation
 */

import { describe, expect, test } from 'bun:test';
import { RationalField } from '../rational_field.js';
import {
  MPolynomialIdeal,
  groebner_basis,
  ideal,
  reduce,
  sPolynomial,
} from './multi_polynomial_ideal.js';
import { MPolynomialRing } from './multi_polynomial_ring.js';

const QQ = RationalField.getInstance();

describe('Gröbner basis', () => {
  describe('sPolynomial', () => {
    test('computes S-polynomial of two polynomials', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      // f = x^2*y - 1
      // g = x*y^2 - x
      const f = R.monomial([2, 1]).sub(R.one());
      const g = R.monomial([1, 2]).sub(R.gen(0));

      const s = sPolynomial(f, g);
      // S(f, g) should eliminate the leading terms
      expect(s.isZero()).toBe(false);
    });

    test('S-polynomial of polynomial with itself is zero', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      const f = R.monomial([2, 1]).add(R.monomial([1, 0]));

      const s = sPolynomial(f, f);
      expect(s.isZero()).toBe(true);
    });
  });

  describe('reduce', () => {
    test('reduces polynomial by divisor', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      // f = x^2 + x + 1
      // g = x + 1
      // f mod g should be 1 (in univariate sense, but multivariate may differ)
      const x = R.gen(0);
      const f = x.pow(2).add(x).add(R.one());
      const g = x.add(R.one());

      const r = reduce(f, [g]);
      // The remainder should have lower degree in x
      const lt = r.leadingTerm();
      if (lt) {
        expect(lt[0][0] ?? 0).toBeLessThan(2);
      }
    });

    test('returns zero when fully reducible', () => {
      const R = new MPolynomialRing(QQ, ['x']);
      const x = R.gen(0);
      // f = x^2, g = x
      // f = x * x, so it reduces to 0 mod [x]
      const f = x.pow(2);
      const g = x;

      const r = reduce(f, [g]);
      expect(r.isZero()).toBe(true);
    });
  });

  describe('groebner_basis', () => {
    test('computes basis for simple ideal', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      const x = R.gen(0);
      const y = R.gen(1);

      // Ideal generated by x, y has Gröbner basis {x, y}
      const gb = groebner_basis([x, y]);

      expect(gb.length).toBeGreaterThan(0);
      // Check that both x and y (or their equivalents) are in the basis
    });

    test('computes basis for Katsura-2', () => {
      // Katsura-2 system: x0 + 2*x1 - 1 = 0, x0^2 + 2*x1^2 - x0 = 0
      const R = new MPolynomialRing(QQ, ['x0', 'x1']);
      const x0 = R.gen(0);
      const x1 = R.gen(1);

      const f1 = x0.add(x1.scalarMul(QQ.__call__(2))).sub(R.one());
      const f2 = x0
        .pow(2)
        .add(x1.pow(2).scalarMul(QQ.__call__(2)))
        .sub(x0);

      const gb = groebner_basis([f1, f2]);

      expect(gb.length).toBeGreaterThan(0);
      // The basis should be able to reduce both f1 and f2 to zero
      for (const f of [f1, f2]) {
        const r = reduce(f, gb);
        expect(r.isZero()).toBe(true);
      }
    });

    test('returns empty for empty input', () => {
      const gb = groebner_basis([]);
      expect(gb).toEqual([]);
    });

    test('handles constant polynomial', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      const one = R.one();

      const gb = groebner_basis([one]);
      expect(gb.length).toBe(1);
      expect(gb[0]!.isConstant()).toBe(true);
    });
  });

  describe('MPolynomialIdeal', () => {
    test('contains checks membership', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      const x = R.gen(0);
      const y = R.gen(1);

      const I = ideal([x, y]);

      // x and y should be in the ideal
      expect(I.contains(x)).toBe(true);
      expect(I.contains(y)).toBe(true);

      // x + y should be in the ideal
      expect(I.contains(x.add(y))).toBe(true);

      // 1 should not be in the ideal (since ideal is proper)
      expect(I.contains(R.one())).toBe(false);
    });

    test('isOne detects unit ideal', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);

      // Ideal (1) is the whole ring
      const I = ideal([R.one()]);
      expect(I.isOne()).toBe(true);

      // Ideal (x, y) is proper
      const J = ideal([R.gen(0), R.gen(1)]);
      expect(J.isOne()).toBe(false);
    });

    test('reduce computes normal form', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      const x = R.gen(0);
      const y = R.gen(1);

      // Ideal (x^2 - y)
      const I = ideal([x.pow(2).sub(y)]);

      // x^3 should reduce to x*y mod (x^2 - y)
      const f = x.pow(3);
      const r = I.reduce(f);

      // r should be equivalent to x*y
      // Check by verifying f - r is in the ideal
      expect(I.contains(f.sub(r))).toBe(true);
    });

    test('toString shows generators', () => {
      const R = new MPolynomialRing(QQ, ['x', 'y']);
      const x = R.gen(0);
      const y = R.gen(1);

      const I = ideal([x, y]);
      const str = I.toString();

      expect(str).toContain('Ideal');
      expect(str).toContain('x');
      expect(str).toContain('y');
    });
  });
});
