/**
 * # Cyclic Groups and Generators
 *
 * Cyclic groups are the simplest type of group and play a central role in
 * cryptography. Nearly all groups used in cryptographic protocols are either
 * cyclic or have cyclic components.
 *
 * ## Mathematical Background
 *
 * A group G is CYCLIC if there exists an element g in G such that every element
 * of G can be written as a power of g:
 *   G = <g> = {g^0, g^1, g^2, ..., g^(n-1)}
 *
 * Such an element g is called a GENERATOR of G.
 *
 * Key facts:
 *   - Every cyclic group of order n is isomorphic to (Z/nZ, +)
 *   - If |G| = n, then G is cyclic iff G has an element of order n
 *   - (Z/pZ)* is cyclic for any prime p
 *   - A cyclic group of order n has phi(n) generators
 *
 * ## Why This Matters for Cryptography
 *
 *   - Diffie-Hellman requires a generator of (Z/p)*
 *   - ECDSA uses generators of elliptic curve groups
 *   - Schnorr signatures work in cyclic groups
 *   - Pairings map between carefully chosen cyclic groups
 */

import { gcd, euler_phi, power_mod, Mod, factor, divisors, Zmod } from 'sagemath-ts';

// =============================================================================
// Example 1: The Prototypical Cyclic Group (Z/nZ, +)
// =============================================================================
console.log("=== Example 1: (Z/nZ, +) - The Prototypical Cyclic Group ===\n");

/**
 * (Z/nZ, +) is cyclic with generator 1.
 * Every element can be written as 1 + 1 + ... + 1 (some number of times).
 */
const n = 6n;
console.log(`The group (Z/${n}Z, +):\n`);

console.log("Generated by 1:");
let powers = "  <1> = { ";
let current = 0n;
for (let i = 0n; i <= n; i++) {
  powers += `${current}`;
  if (i < n) powers += ", ";
  current = (current + 1n) % n;
}
powers += " }";
console.log(powers);

// Check other generators
console.log("\nWhich elements generate Z/6Z?");
for (let g = 0n; g < n; g++) {
  const generated = new Set<bigint>();
  let elem = 0n;
  for (let i = 0n; i < n; i++) {
    generated.add(elem);
    elem = (elem + g) % n;
  }

  const isGenerator = generated.size === Number(n);
  const gcdWithN = gcd(g, n);
  console.log(`  g = ${g}: |<${g}>| = ${generated.size}, gcd(${g}, ${n}) = ${gcdWithN}, generator? ${isGenerator}`);
}

console.log("\nKey insight: g generates Z/nZ iff gcd(g, n) = 1");
console.log(`Number of generators = phi(${n}) = ${euler_phi(n)}`);

console.log();

// =============================================================================
// Example 2: Cyclic Multiplicative Groups (Z/pZ)*
// =============================================================================
console.log("=== Example 2: (Z/pZ)* - Cyclic Multiplicative Group ===\n");

/**
 * For prime p, (Z/pZ)* is a cyclic group of order p-1.
 * A generator is called a "primitive root" modulo p.
 */
const p = 7n;
const Zp = Zmod(p);

console.log(`(Z/${p}Z)* has order ${p - 1n}\n`);

console.log("Finding generators (primitive roots) of (Z/7Z)*:");
for (let g = 1n; g < p; g++) {
  const generated: bigint[] = [];
  let elem = 1n;

  for (let i = 0n; i < p - 1n; i++) {
    generated.push(elem);
    elem = (elem * g) % p;
  }

  const order = new Set(generated).size;
  const isGenerator = order === Number(p - 1n);

  console.log(`  g = ${g}: powers = {${generated.join(', ')}}, order = ${order}, primitive root? ${isGenerator}`);
}

console.log();

// =============================================================================
// Example 3: Computing Element Orders
// =============================================================================
console.log("=== Example 3: Computing Element Orders ===\n");

/**
 * The order of an element g is the smallest positive k such that g^k = e.
 * An element is a generator iff its order equals the group order.
 */
function elementOrder(g: bigint, n: bigint): bigint {
  // In (Z/nZ)*, compute order of g
  if (gcd(g, n) !== 1n) {
    throw new Error("g must be coprime to n");
  }

  const groupOrder = euler_phi(n);
  let order = 1n;
  let current = g % n;

  while (current !== 1n) {
    current = (current * g) % n;
    order++;
    if (order > groupOrder) {
      throw new Error("Element order exceeds group order");
    }
  }

  return order;
}

const modulus = 13n;
console.log(`Orders of elements in (Z/${modulus}Z)*:\n`);

const groupOrder = euler_phi(modulus);
console.log(`Group order = phi(${modulus}) = ${groupOrder}\n`);

for (let g = 1n; g < modulus; g++) {
  const ord = elementOrder(g, modulus);
  const divides = groupOrder % ord === 0n;
  const isGen = ord === groupOrder;
  console.log(`  ord(${g.toString().padStart(2)}) = ${ord.toString().padStart(2)}  (divides ${groupOrder}? ${divides}, generator? ${isGen})`);
}

console.log(`\nLagrange's Theorem: Element order always divides group order!`);

console.log();

// =============================================================================
// Example 4: Subgroups of Cyclic Groups
// =============================================================================
console.log("=== Example 4: Subgroups of Cyclic Groups ===\n");

/**
 * A cyclic group of order n has exactly one subgroup for each divisor of n.
 * If G = <g> has order n, and d | n, then <g^(n/d)> is the unique subgroup of order d.
 */
const N = 12n;
console.log(`Subgroups of the cyclic group of order ${N}:\n`);

const divs = divisors(N);
console.log(`Divisors of ${N}: ${divs.join(', ')}\n`);

for (const d of divs) {
  console.log(`  Subgroup of order ${d}: generated by g^${N/d}`);
  console.log(`    Elements: g^0, g^${N/d}, g^${2n*(N/d)}, ..., g^${(d-1n)*(N/d)}`);
}

console.log(`\nTotal number of subgroups: ${divs.length}`);
console.log("Every subgroup of a cyclic group is itself cyclic!");

console.log();

// =============================================================================
// Example 5: Counting Generators
// =============================================================================
console.log("=== Example 5: Counting Generators ===\n");

/**
 * A cyclic group of order n has exactly phi(n) generators.
 * The generators are g^k where gcd(k, n) = 1.
 */
const ord = 12n;
console.log(`In a cyclic group of order ${ord}:\n`);

console.log("Generator powers (k where gcd(k, n) = 1):");
const genPowers: bigint[] = [];
for (let k = 1n; k <= ord; k++) {
  if (gcd(k, ord) === 1n) {
    genPowers.push(k);
  }
}
console.log(`  k in {${genPowers.join(', ')}}`);
console.log(`  Count: ${genPowers.length} = phi(${ord}) = ${euler_phi(ord)}`);

console.log();

// =============================================================================
// Example 6: Finding Primitive Roots
// =============================================================================
console.log("=== Example 6: Finding Primitive Roots (Generators of (Z/pZ)*) ===\n");

/**
 * Algorithm to find a primitive root modulo prime p:
 * 1. Compute p - 1 and its prime factorization
 * 2. For each candidate g, check if g^((p-1)/q) != 1 for each prime q | (p-1)
 */
function findPrimitiveRoot(p: bigint): bigint {
  if (p === 2n) return 1n;

  const pMinus1 = p - 1n;
  const factors = factor(pMinus1);
  const primeFactors = factors.filter(([f]) => f > 0n).map(([f]) => f);

  for (let g = 2n; g < p; g++) {
    let isPrimitive = true;

    for (const q of primeFactors) {
      const exp = pMinus1 / q;
      if (power_mod(g, exp, p) === 1n) {
        isPrimitive = false;
        break;
      }
    }

    if (isPrimitive) {
      return g;
    }
  }

  throw new Error("No primitive root found");
}

const prime = 23n;
console.log(`Finding a primitive root modulo ${prime}:\n`);

const pMinus1 = prime - 1n;
console.log(`  ${prime} - 1 = ${pMinus1}`);
const factors = factor(pMinus1);
console.log(`  Factorization: ${factors.map(([p, e]) => e === 1n ? `${p}` : `${p}^${e}`).join(' * ')}`);
console.log(`  Prime factors of ${pMinus1}: ${factors.filter(([f]) => f > 0n).map(([f]) => f).join(', ')}\n`);

const primitiveRoot = findPrimitiveRoot(prime);
console.log(`Smallest primitive root: ${primitiveRoot}`);

// Verify
console.log("\nVerifying powers of g = 5 generate all of (Z/23Z)*:");
const generated = new Set<bigint>();
let elem = 1n;
for (let i = 0n; i < prime - 1n; i++) {
  generated.add(elem);
  elem = (elem * primitiveRoot) % prime;
}
console.log(`  |<${primitiveRoot}>| = ${generated.size} = ${prime - 1n}`);

console.log();

// =============================================================================
// Example 7: All Generators of (Z/pZ)*
// =============================================================================
console.log("=== Example 7: Finding All Generators ===\n");

/**
 * Once we have one primitive root g, all others are g^k where gcd(k, p-1) = 1.
 */
const pr = 11n;
const g = findPrimitiveRoot(pr);
const order = pr - 1n;

console.log(`(Z/${pr}Z)* has order ${order}`);
console.log(`Primitive root: ${g}\n`);

console.log(`All primitive roots mod ${pr} (powers g^k where gcd(k, ${order}) = 1):`);
const allGens: bigint[] = [];

for (let k = 1n; k < order; k++) {
  if (gcd(k, order) === 1n) {
    const gen = power_mod(g, k, pr);
    allGens.push(gen);
  }
}

allGens.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
console.log(`  {${allGens.join(', ')}}`);
console.log(`  Count: ${allGens.length} = phi(${order}) = ${euler_phi(order)}`);

console.log();

// =============================================================================
// Example 8: Structure of (Z/nZ)* for Composite n
// =============================================================================
console.log("=== Example 8: (Z/nZ)* for Composite n ===\n");

/**
 * (Z/nZ)* is not always cyclic!
 * It's cyclic iff n = 1, 2, 4, p^k, or 2p^k for odd prime p.
 */
function isCyclic(n: bigint): boolean {
  if (n === 1n || n === 2n || n === 4n) return true;

  const factors = factor(n);
  const primeFactors = factors.filter(([p]) => p > 1n);

  // Check if n = p^k for odd prime p
  if (primeFactors.length === 1) {
    const [prime] = primeFactors[0]!;
    return prime !== 2n;  // p^k for odd p is cyclic
  }

  // Check if n = 2 * p^k for odd prime p
  if (primeFactors.length === 2) {
    const [[p1, e1], [p2, e2]] = primeFactors;
    if (p1 === 2n && e1 === 1n && p2! > 2n) return true;
    if (p2 === 2n && e2 === 1n && p1! > 2n) return true;
  }

  return false;
}

const testModuli = [5n, 8n, 9n, 10n, 12n, 15n, 16n, 18n, 25n];

console.log("Which (Z/nZ)* are cyclic?");
for (const mod of testModuli) {
  const phi = euler_phi(mod);
  const cyclic = isCyclic(mod);

  // Find maximum element order
  let maxOrder = 1n;
  for (let g = 1n; g < mod; g++) {
    if (gcd(g, mod) === 1n) {
      const ord = elementOrder(g, mod);
      if (ord > maxOrder) maxOrder = ord;
    }
  }

  console.log(`  (Z/${mod.toString().padStart(2)}Z)*: phi = ${phi.toString().padStart(2)}, max order = ${maxOrder.toString().padStart(2)}, cyclic? ${cyclic}`);
}

console.log("\n(Z/8Z)* = {1, 3, 5, 7} is the Klein four-group, not cyclic!");

console.log();

// =============================================================================
// Exercise: Implement Primitive Root Finder
// =============================================================================
console.log("=== Exercise: Verify a Primitive Root ===\n");

/**
 * EXERCISE: Verify that 2 is a primitive root modulo 13.
 */
const testPrime = 13n;
const testGen = 2n;

console.log(`Verifying that ${testGen} is a primitive root mod ${testPrime}:\n`);

// Generate all powers
const powers2: bigint[] = [];
let power = 1n;
for (let i = 0n; i < testPrime - 1n; i++) {
  powers2.push(power);
  power = (power * testGen) % testPrime;
}

console.log(`  Powers of ${testGen}: {${powers2.join(', ')}}`);
console.log(`  Distinct values: ${new Set(powers2).size}`);
console.log(`  Group order: ${testPrime - 1n}`);
console.log(`  Is ${testGen} a primitive root? ${new Set(powers2).size === Number(testPrime - 1n)}`);

console.log();

// =============================================================================
// Cryptographic Application: Diffie-Hellman Setup
// =============================================================================
console.log("=== Cryptographic Application: Diffie-Hellman Key Exchange ===\n");

/**
 * Diffie-Hellman key exchange requires:
 * 1. A large prime p
 * 2. A generator g of (Z/pZ)*
 *
 * The security relies on the Discrete Log Problem being hard in this group.
 */
console.log("Diffie-Hellman Key Exchange Setup:\n");

// Small example (NOT cryptographically secure!)
const dhP = 23n;
const dhG = findPrimitiveRoot(dhP);

console.log(`  Prime p = ${dhP}`);
console.log(`  Generator g = ${dhG}`);
console.log(`  Group (Z/${dhP}Z)* has order ${dhP - 1n}\n`);

// Alice's private key
const alicePrivate = 6n;
const alicePublic = power_mod(dhG, alicePrivate, dhP);
console.log(`  Alice: private a = ${alicePrivate}, public A = g^a = ${dhG}^${alicePrivate} = ${alicePublic}`);

// Bob's private key
const bobPrivate = 15n;
const bobPublic = power_mod(dhG, bobPrivate, dhP);
console.log(`  Bob: private b = ${bobPrivate}, public B = g^b = ${dhG}^${bobPrivate} = ${bobPublic}`);

// Shared secret
const aliceComputes = power_mod(bobPublic, alicePrivate, dhP);
const bobComputes = power_mod(alicePublic, bobPrivate, dhP);

console.log(`\n  Alice computes: B^a = ${bobPublic}^${alicePrivate} = ${aliceComputes}`);
console.log(`  Bob computes: A^b = ${alicePublic}^${bobPrivate} = ${bobComputes}`);
console.log(`  Shared secret: ${aliceComputes}`);

console.log("\nThe security of DH depends on finding discrete logs being hard!");
console.log("For cryptographic use, p should be at least 2048 bits.");
