/**
 * Property tests for arithmetic functions
 * Compares sagemath-ts output with real SageMath output
 *
 * This test file parses output from tests/property/sage/arith.sage
 * and verifies that our TypeScript implementation produces identical results.
 *
 * Usage:
 *   bun test tests/property/typescript/arith-comparison.test.ts
 *
 * Or via the comparison runner:
 *   bun run test:property:sage
 */

import { describe, test, expect, beforeAll } from 'bun:test';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

// Import from sagemath-ts package
import {
  gcd,
  lcm,
  xgcd,
  factor,
  is_prime,
  is_prime_power,
  sqrt_mod,
  power_mod,
  inverse_mod,
  euler_phi,
  moebius,
  kronecker_symbol,
  divisors,
  sigma,
  radical,
  prime_range,
  valuation,
  next_prime,
  previous_prime,
  isqrt,
  is_square,
  is_squarefree,
  squarefree_part,
  prime_factors,
  crt,
  CRT_list,
  number_of_divisors,
  type Factorization,
} from '../../../packages/sagemath-ts/src/index.js';

// Path to SageMath output file (generated by run-comparison.sh)
const SAGE_OUTPUT_PATH = join(
  import.meta.dir,
  '..',
  'transcripts',
  'sage',
  'arith.txt'
);

/**
 * Parsed SageMath test result
 */
interface SageTestResult {
  operation: string;
  result: string;
}

/**
 * Parse SageMath output file into structured test results
 */
function parseSageOutput(content: string): SageTestResult[] {
  const results: SageTestResult[] = [];
  const lines = content.split('\n');

  let currentOperation = '';

  for (const line of lines) {
    if (line.startsWith('# ') && !line.startsWith('# ===')) {
      // This is an operation line
      currentOperation = line.substring(2);
    } else if (line.startsWith('RESULT: ')) {
      // This is a result line
      const result = line.substring(8);
      results.push({
        operation: currentOperation,
        result,
      });
      currentOperation = '';
    }
  }

  return results;
}

/**
 * Format a Factorization to match SageMath output format
 * SageMath: [(2, 2), (3, 1)]
 */
function formatFactorization(f: Factorization): string {
  if (f.length === 0) {
    return '[]';
  }
  const pairs = f.map(([prime, exp]) => `(${prime}, ${exp})`);
  return `[${pairs.join(', ')}]`;
}

/**
 * Format an array of bigints to match SageMath list output
 */
function formatBigintArray(arr: bigint[]): string {
  return `[${arr.join(', ')}]`;
}

// Store parsed SageMath results
let sageResults: SageTestResult[] = [];
let sageOutputAvailable = false;

// Map from operation string to index for easier lookup
let resultMap: Map<string, string> = new Map();

describe('Arithmetic Function Property Tests - SageMath Comparison', () => {
  beforeAll(() => {
    if (existsSync(SAGE_OUTPUT_PATH)) {
      const content = readFileSync(SAGE_OUTPUT_PATH, 'utf-8');
      sageResults = parseSageOutput(content);
      sageOutputAvailable = true;

      // Build map for easier lookup
      for (const r of sageResults) {
        resultMap.set(r.operation, r.result);
      }
    } else {
      console.warn(
        '\n  SageMath output not available. Run "bun run test:property:sage" to generate.\n'
      );
      console.warn(`  Expected path: ${SAGE_OUTPUT_PATH}\n`);
    }
  });

  // Helper to get expected result
  function getExpected(op: string): string | undefined {
    return resultMap.get(op);
  }

  // =============================================================================
  // GCD Tests
  // =============================================================================
  describe('gcd', () => {
    test('gcd(12, 8)', () => {
      const result = gcd(12n, 8n);
      expect(result.toString()).toBe(getExpected('gcd(12, 8)') ?? '4');
    });

    test('gcd(100, 35)', () => {
      const result = gcd(100n, 35n);
      expect(result.toString()).toBe(getExpected('gcd(100, 35)') ?? '5');
    });

    test('gcd(-24, 18)', () => {
      const result = gcd(-24n, 18n);
      expect(result.toString()).toBe(getExpected('gcd(-24, 18)') ?? '6');
    });

    test('gcd(0, 5)', () => {
      const result = gcd(0n, 5n);
      expect(result.toString()).toBe(getExpected('gcd(0, 5)') ?? '5');
    });

    test('gcd(1000000, 999999)', () => {
      const result = gcd(1000000n, 999999n);
      expect(result.toString()).toBe(getExpected('gcd(1000000, 999999)') ?? '1');
    });

    test('gcd(2**100, 2**50)', () => {
      const result = gcd(2n ** 100n, 2n ** 50n);
      expect(result.toString()).toBe(getExpected('gcd(2**100, 2**50)') ?? (2n ** 50n).toString());
    });
  });

  // =============================================================================
  // LCM Tests
  // =============================================================================
  describe('lcm', () => {
    test('lcm(4, 6)', () => {
      const result = lcm(4n, 6n);
      expect(result.toString()).toBe(getExpected('lcm(4, 6)') ?? '12');
    });

    test('lcm(12, 18)', () => {
      const result = lcm(12n, 18n);
      expect(result.toString()).toBe(getExpected('lcm(12, 18)') ?? '36');
    });

    test('lcm(0, 5)', () => {
      const result = lcm(0n, 5n);
      expect(result.toString()).toBe(getExpected('lcm(0, 5)') ?? '0');
    });

    test('lcm(7, 11)', () => {
      const result = lcm(7n, 11n);
      expect(result.toString()).toBe(getExpected('lcm(7, 11)') ?? '77');
    });

    test('lcm(100, 35)', () => {
      const result = lcm(100n, 35n);
      expect(result.toString()).toBe(getExpected('lcm(100, 35)') ?? '700');
    });
  });

  // =============================================================================
  // XGCD Tests
  // =============================================================================
  describe('xgcd', () => {
    test('xgcd(6, 4)', () => {
      const [g, s, t] = xgcd(6n, 4n);
      const result = `[${g}, ${s}, ${t}]`;
      expect(result).toBe(getExpected('xgcd(6, 4)') ?? '[2, 1, -1]');
      // Verify the identity: g = s*a + t*b
      expect(g).toBe(s * 6n + t * 4n);
    });

    test('xgcd(240, 46)', () => {
      const [g, s, t] = xgcd(240n, 46n);
      const result = `[${g}, ${s}, ${t}]`;
      expect(result).toBe(getExpected('xgcd(240, 46)') ?? '[2, -9, 47]');
      expect(g).toBe(s * 240n + t * 46n);
    });

    test('xgcd(17, 5)', () => {
      const [g, s, t] = xgcd(17n, 5n);
      const result = `[${g}, ${s}, ${t}]`;
      expect(result).toBe(getExpected('xgcd(17, 5)') ?? '[1, -2, 7]');
      expect(g).toBe(s * 17n + t * 5n);
    });

    test('xgcd(100, 23)', () => {
      const [g, s, t] = xgcd(100n, 23n);
      const result = `[${g}, ${s}, ${t}]`;
      expect(result).toBe(getExpected('xgcd(100, 23)') ?? '[1, 3, -13]');
      expect(g).toBe(s * 100n + t * 23n);
    });

    test('xgcd(-12, 18)', () => {
      const [g, s, t] = xgcd(-12n, 18n);
      const result = `[${g}, ${s}, ${t}]`;
      // Note: xgcd has multiple valid solutions; compare against SageMath when available
      if (sageOutputAvailable) {
        expect(result).toBe(getExpected('xgcd(-12, 18)'));
      }
      // Always verify the identity: g = s*a + t*b
      expect(g).toBe(s * (-12n) + t * 18n);
      expect(g).toBe(6n);
    });
  });

  // =============================================================================
  // Factor Tests
  // =============================================================================
  describe('factor', () => {
    test('factor(12)', () => {
      const f = factor(12n);
      const result = formatFactorization(f);
      expect(result).toBe(getExpected('factor(12)') ?? '[(2, 2), (3, 1)]');
    });

    test('factor(100)', () => {
      const f = factor(100n);
      const result = formatFactorization(f);
      expect(result).toBe(getExpected('factor(100)') ?? '[(2, 2), (5, 2)]');
    });

    test('factor(1001)', () => {
      const f = factor(1001n);
      const result = formatFactorization(f);
      expect(result).toBe(getExpected('factor(1001)') ?? '[(7, 1), (11, 1), (13, 1)]');
    });

    test('factor(2**31-1)', () => {
      const f = factor(2n ** 31n - 1n);
      const result = formatFactorization(f);
      // 2^31 - 1 = 2147483647 is prime
      expect(result).toBe(getExpected('factor(2**31-1)') ?? '[(2147483647, 1)]');
    });

    test('factor(1)', () => {
      const f = factor(1n);
      const result = formatFactorization(f);
      expect(result).toBe(getExpected('factor(1)') ?? '[]');
    });

    test('factor(2)', () => {
      const f = factor(2n);
      const result = formatFactorization(f);
      expect(result).toBe(getExpected('factor(2)') ?? '[(2, 1)]');
    });

    test('factor(1000000)', () => {
      const f = factor(1000000n);
      const result = formatFactorization(f);
      expect(result).toBe(getExpected('factor(1000000)') ?? '[(2, 6), (5, 6)]');
    });

    test('factor(97)', () => {
      const f = factor(97n);
      const result = formatFactorization(f);
      expect(result).toBe(getExpected('factor(97)') ?? '[(97, 1)]');
    });
  });

  // =============================================================================
  // is_prime Tests
  // =============================================================================
  describe('is_prime', () => {
    test('is_prime(2)', () => {
      const result = is_prime(2n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(2)') ?? 'True'
      );
    });

    test('is_prime(17)', () => {
      const result = is_prime(17n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(17)') ?? 'True'
      );
    });

    test('is_prime(100)', () => {
      const result = is_prime(100n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(100)') ?? 'False'
      );
    });

    test('is_prime(2**61-1)', () => {
      const result = is_prime(2n ** 61n - 1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(2**61-1)') ?? 'True'
      );
    });

    test('is_prime(1)', () => {
      const result = is_prime(1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(1)') ?? 'False'
      );
    });

    test('is_prime(0)', () => {
      const result = is_prime(0n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(0)') ?? 'False'
      );
    });

    test('is_prime(-7)', () => {
      const result = is_prime(-7n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(-7)') ?? 'False'
      );
    });

    test('is_prime(104729)', () => {
      const result = is_prime(104729n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(104729)') ?? 'True'
      );
    });

    test('is_prime(561) - Carmichael number', () => {
      const result = is_prime(561n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(561)') ?? 'False'
      );
    });

    test('is_prime(2**89-1) - Mersenne prime', () => {
      const result = is_prime(2n ** 89n - 1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(2**89-1)') ?? 'True'
      );
    });
  });

  // =============================================================================
  // is_prime_power Tests
  // =============================================================================
  describe('is_prime_power', () => {
    test('is_prime_power(8)', () => {
      const result = is_prime_power(8n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime_power(8)') ?? 'True'
      );
    });

    test('is_prime_power(9)', () => {
      const result = is_prime_power(9n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime_power(9)') ?? 'True'
      );
    });

    test('is_prime_power(12)', () => {
      const result = is_prime_power(12n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime_power(12)') ?? 'False'
      );
    });

    test('is_prime_power(17)', () => {
      const result = is_prime_power(17n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime_power(17)') ?? 'True'
      );
    });

    test('is_prime_power(1)', () => {
      const result = is_prime_power(1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime_power(1)') ?? 'False'
      );
    });

    test('is_prime_power(8, get_data=True)', () => {
      const [p, k] = is_prime_power(8n, true);
      const result = `[${p}, ${k}]`;
      expect(result).toBe(getExpected('is_prime_power(8, get_data=True)') ?? '[2, 3]');
    });

    test('is_prime_power(81, get_data=True)', () => {
      const [p, k] = is_prime_power(81n, true);
      const result = `[${p}, ${k}]`;
      expect(result).toBe(getExpected('is_prime_power(81, get_data=True)') ?? '[3, 4]');
    });

    test('is_prime_power(12, get_data=True)', () => {
      const [p, k] = is_prime_power(12n, true);
      const result = `[${p}, ${k}]`;
      expect(result).toBe(getExpected('is_prime_power(12, get_data=True)') ?? '[12, 0]');
    });
  });

  // =============================================================================
  // sqrt_mod Tests
  // =============================================================================
  describe('sqrt_mod', () => {
    test('sqrt_mod(2, 7, all=True)', () => {
      const result = sqrt_mod(2n, 7n, true);
      expect(formatBigintArray(result)).toBe(getExpected('sqrt_mod(2, 7, all=True)') ?? '[3, 4]');
    });

    test('sqrt_mod(3, 11, all=True)', () => {
      const result = sqrt_mod(3n, 11n, true);
      expect(formatBigintArray(result)).toBe(getExpected('sqrt_mod(3, 11, all=True)') ?? '[5, 6]');
    });

    test('sqrt_mod(4, 13, all=True)', () => {
      const result = sqrt_mod(4n, 13n, true);
      expect(formatBigintArray(result)).toBe(getExpected('sqrt_mod(4, 13, all=True)') ?? '[2, 11]');
      // Verify: 2^2 = 4, 11^2 = 121 = 9*13 + 4 = 4 mod 13
      for (const r of result) {
        expect((r * r) % 13n).toBe(4n);
      }
    });

    test('sqrt_mod(2, 7)', () => {
      const result = sqrt_mod(2n, 7n);
      // Either 3 or 4 is valid
      expect(['3', '4']).toContain(result?.toString());
    });

    test('sqrt_mod(3, 5) - not a QR', () => {
      const result = sqrt_mod(3n, 5n);
      expect(result).toBe(null);
    });

    test('sqrt_mod(0, 7)', () => {
      const result = sqrt_mod(0n, 7n);
      expect(result?.toString()).toBe(getExpected('sqrt_mod(0, 7)') ?? '0');
    });

    test('sqrt_mod(1, 101, all=True)', () => {
      const result = sqrt_mod(1n, 101n, true);
      expect(formatBigintArray(result)).toBe(getExpected('sqrt_mod(1, 101)') ?? '[1, 100]');
    });

    test('sqrt_mod(4, 101, all=True)', () => {
      const result = sqrt_mod(4n, 101n, true);
      expect(formatBigintArray(result)).toBe(getExpected('sqrt_mod(4, 101)') ?? '[2, 99]');
    });

    test('sqrt_mod(2, 17, all=True) - Tonelli-Shanks', () => {
      const result = sqrt_mod(2n, 17n, true);
      expect(formatBigintArray(result)).toBe(getExpected('sqrt_mod(2, 17, all=True)') ?? '[6, 11]');
    });
  });

  // =============================================================================
  // power_mod Tests
  // =============================================================================
  describe('power_mod', () => {
    test('power_mod(2, 10, 1000)', () => {
      const result = power_mod(2n, 10n, 1000n);
      expect(result.toString()).toBe(getExpected('power_mod(2, 10, 1000)') ?? '24');
    });

    test('power_mod(3, -1, 7)', () => {
      const result = power_mod(3n, -1n, 7n);
      expect(result.toString()).toBe(getExpected('power_mod(3, -1, 7)') ?? '5');
    });

    test('power_mod(2, 100, 997)', () => {
      const result = power_mod(2n, 100n, 997n);
      expect(result.toString()).toBe(getExpected('power_mod(2, 100, 997)') ?? '907');
    });

    test('power_mod(5, 0, 13)', () => {
      const result = power_mod(5n, 0n, 13n);
      expect(result.toString()).toBe(getExpected('power_mod(5, 0, 13)') ?? '1');
    });

    test('power_mod(7, 1, 101)', () => {
      const result = power_mod(7n, 1n, 101n);
      expect(result.toString()).toBe(getExpected('power_mod(7, 1, 101)') ?? '7');
    });

    test('power_mod(2, 256, 1000000007)', () => {
      const result = power_mod(2n, 256n, 1000000007n);
      expect(result.toString()).toBe(getExpected('power_mod(2, 256, 1000000007)') ?? '792845266');
    });
  });

  // =============================================================================
  // inverse_mod Tests
  // =============================================================================
  describe('inverse_mod', () => {
    test('inverse_mod(3, 7)', () => {
      const result = inverse_mod(3n, 7n);
      expect(result.toString()).toBe(getExpected('inverse_mod(3, 7)') ?? '5');
      // Verify: 3 * 5 = 15 = 1 mod 7
      expect((3n * result) % 7n).toBe(1n);
    });

    test('inverse_mod(5, 11)', () => {
      const result = inverse_mod(5n, 11n);
      expect(result.toString()).toBe(getExpected('inverse_mod(5, 11)') ?? '9');
      expect((5n * result) % 11n).toBe(1n);
    });

    test('inverse_mod(17, 101)', () => {
      const result = inverse_mod(17n, 101n);
      expect(result.toString()).toBe(getExpected('inverse_mod(17, 101)') ?? '6');
      expect((17n * result) % 101n).toBe(1n);
    });

    test('inverse_mod(2, 1000000007)', () => {
      const result = inverse_mod(2n, 1000000007n);
      expect(result.toString()).toBe(getExpected('inverse_mod(2, 1000000007)') ?? '500000004');
      expect((2n * result) % 1000000007n).toBe(1n);
    });
  });

  // =============================================================================
  // euler_phi Tests
  // =============================================================================
  describe('euler_phi', () => {
    test('euler_phi(1)', () => {
      const result = euler_phi(1n);
      expect(result.toString()).toBe(getExpected('euler_phi(1)') ?? '1');
    });

    test('euler_phi(12)', () => {
      const result = euler_phi(12n);
      expect(result.toString()).toBe(getExpected('euler_phi(12)') ?? '4');
    });

    test('euler_phi(100)', () => {
      const result = euler_phi(100n);
      expect(result.toString()).toBe(getExpected('euler_phi(100)') ?? '40');
    });

    test('euler_phi(97) - prime', () => {
      const result = euler_phi(97n);
      expect(result.toString()).toBe(getExpected('euler_phi(97)') ?? '96');
    });

    test('euler_phi(1000)', () => {
      const result = euler_phi(1000n);
      expect(result.toString()).toBe(getExpected('euler_phi(1000)') ?? '400');
    });

    test('euler_phi(2**10)', () => {
      const result = euler_phi(2n ** 10n);
      expect(result.toString()).toBe(getExpected('euler_phi(2**10)') ?? '512');
    });
  });

  // =============================================================================
  // moebius Tests
  // =============================================================================
  describe('moebius', () => {
    test('moebius(1)', () => {
      const result = moebius(1n);
      expect(result.toString()).toBe(getExpected('moebius(1)') ?? '1');
    });

    test('moebius(2)', () => {
      const result = moebius(2n);
      expect(result.toString()).toBe(getExpected('moebius(2)') ?? '-1');
    });

    test('moebius(6) - two distinct primes', () => {
      const result = moebius(6n);
      expect(result.toString()).toBe(getExpected('moebius(6)') ?? '1');
    });

    test('moebius(4) - has squared factor', () => {
      const result = moebius(4n);
      expect(result.toString()).toBe(getExpected('moebius(4)') ?? '0');
    });

    test('moebius(30) - three distinct primes', () => {
      const result = moebius(30n);
      expect(result.toString()).toBe(getExpected('moebius(30)') ?? '-1');
    });

    test('moebius(5) - prime', () => {
      const result = moebius(5n);
      expect(result.toString()).toBe(getExpected('moebius(5)') ?? '-1');
    });

    test('moebius(12) - has squared factor', () => {
      const result = moebius(12n);
      expect(result.toString()).toBe(getExpected('moebius(12)') ?? '0');
    });
  });

  // =============================================================================
  // kronecker_symbol Tests
  // =============================================================================
  describe('kronecker_symbol', () => {
    test('kronecker_symbol(2, 7)', () => {
      const result = kronecker_symbol(2n, 7n);
      expect(result.toString()).toBe(getExpected('kronecker_symbol(2, 7)') ?? '1');
    });

    test('kronecker_symbol(3, 11)', () => {
      const result = kronecker_symbol(3n, 11n);
      expect(result.toString()).toBe(getExpected('kronecker_symbol(3, 11)') ?? '1');
    });

    test('kronecker_symbol(5, 13)', () => {
      const result = kronecker_symbol(5n, 13n);
      expect(result.toString()).toBe(getExpected('kronecker_symbol(5, 13)') ?? '-1');
    });

    test('kronecker_symbol(2, 3)', () => {
      const result = kronecker_symbol(2n, 3n);
      expect(result.toString()).toBe(getExpected('kronecker_symbol(2, 3)') ?? '-1');
    });

    test('kronecker_symbol(3, 5)', () => {
      const result = kronecker_symbol(3n, 5n);
      expect(result.toString()).toBe(getExpected('kronecker_symbol(3, 5)') ?? '-1');
    });

    test('kronecker_symbol(0, 5)', () => {
      const result = kronecker_symbol(0n, 5n);
      expect(result.toString()).toBe(getExpected('kronecker_symbol(0, 5)') ?? '0');
    });

    test('kronecker_symbol(5, 1)', () => {
      const result = kronecker_symbol(5n, 1n);
      expect(result.toString()).toBe(getExpected('kronecker_symbol(5, 1)') ?? '1');
    });
  });

  // =============================================================================
  // divisors Tests
  // =============================================================================
  describe('divisors', () => {
    test('divisors(12)', () => {
      const result = divisors(12n);
      expect(formatBigintArray(result)).toBe(getExpected('divisors(12)') ?? '[1, 2, 3, 4, 6, 12]');
    });

    test('divisors(100)', () => {
      const result = divisors(100n);
      expect(formatBigintArray(result)).toBe(
        getExpected('divisors(100)') ?? '[1, 2, 4, 5, 10, 20, 25, 50, 100]'
      );
    });

    test('divisors(1)', () => {
      const result = divisors(1n);
      expect(formatBigintArray(result)).toBe(getExpected('divisors(1)') ?? '[1]');
    });

    test('divisors(97) - prime', () => {
      const result = divisors(97n);
      expect(formatBigintArray(result)).toBe(getExpected('divisors(97)') ?? '[1, 97]');
    });

    test('divisors(60)', () => {
      const result = divisors(60n);
      expect(formatBigintArray(result)).toBe(
        getExpected('divisors(60)') ?? '[1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60]'
      );
    });
  });

  // =============================================================================
  // sigma Tests
  // =============================================================================
  describe('sigma', () => {
    test('sigma(12, 1)', () => {
      const result = sigma(12n, 1n);
      expect(result.toString()).toBe(getExpected('sigma(12, 1)') ?? '28');
    });

    test('sigma(12, 0) - number of divisors', () => {
      const result = sigma(12n, 0n);
      expect(result.toString()).toBe(getExpected('sigma(12, 0)') ?? '6');
    });

    test('sigma(12, 2) - sum of squares', () => {
      const result = sigma(12n, 2n);
      expect(result.toString()).toBe(getExpected('sigma(12, 2)') ?? '210');
    });

    test('sigma(100, 1)', () => {
      const result = sigma(100n, 1n);
      expect(result.toString()).toBe(getExpected('sigma(100, 1)') ?? '217');
    });

    test('sigma(1, 1)', () => {
      const result = sigma(1n, 1n);
      expect(result.toString()).toBe(getExpected('sigma(1, 1)') ?? '1');
    });
  });

  // =============================================================================
  // radical Tests
  // =============================================================================
  describe('radical', () => {
    test('radical(12)', () => {
      const result = radical(12n);
      expect(result.toString()).toBe(getExpected('radical(12)') ?? '6');
    });

    test('radical(100)', () => {
      const result = radical(100n);
      expect(result.toString()).toBe(getExpected('radical(100)') ?? '10');
    });

    test('radical(1)', () => {
      const result = radical(1n);
      expect(result.toString()).toBe(getExpected('radical(1)') ?? '1');
    });

    test('radical(97) - prime', () => {
      const result = radical(97n);
      expect(result.toString()).toBe(getExpected('radical(97)') ?? '97');
    });

    test('radical(72)', () => {
      const result = radical(72n);
      expect(result.toString()).toBe(getExpected('radical(72)') ?? '6');
    });
  });

  // =============================================================================
  // prime_range Tests
  // =============================================================================
  describe('prime_range', () => {
    test('prime_range(20)', () => {
      const result = prime_range(20n);
      expect(formatBigintArray(result)).toBe(
        getExpected('prime_range(20)') ?? '[2, 3, 5, 7, 11, 13, 17, 19]'
      );
    });

    test('prime_range(10, 30)', () => {
      const result = prime_range(10n, 30n);
      expect(formatBigintArray(result)).toBe(
        getExpected('prime_range(10, 30)') ?? '[11, 13, 17, 19, 23, 29]'
      );
    });

    test('prime_range(100, 120)', () => {
      const result = prime_range(100n, 120n);
      expect(formatBigintArray(result)).toBe(
        getExpected('prime_range(100, 120)') ?? '[101, 103, 107, 109, 113]'
      );
    });

    test('prime_range(2, 3)', () => {
      const result = prime_range(2n, 3n);
      expect(formatBigintArray(result)).toBe(getExpected('prime_range(2, 3)') ?? '[2]');
    });

    test('prime_range(1000, 1050)', () => {
      const result = prime_range(1000n, 1050n);
      expect(formatBigintArray(result)).toBe(
        getExpected('prime_range(1000, 1050)') ?? '[1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049]'
      );
    });
  });

  // =============================================================================
  // valuation Tests
  // =============================================================================
  describe('valuation', () => {
    test('valuation(24, 2)', () => {
      const result = valuation(24n, 2n);
      expect(result.toString()).toBe(getExpected('valuation(24, 2)') ?? '3');
    });

    test('valuation(100, 5)', () => {
      const result = valuation(100n, 5n);
      expect(result.toString()).toBe(getExpected('valuation(100, 5)') ?? '2');
    });

    test('valuation(7, 2) - odd number', () => {
      const result = valuation(7n, 2n);
      expect(result.toString()).toBe(getExpected('valuation(7, 2)') ?? '0');
    });

    test('valuation(1000, 10)', () => {
      const result = valuation(1000n, 10n);
      expect(result.toString()).toBe(getExpected('valuation(1000, 10)') ?? '3');
    });

    test('valuation(81, 3)', () => {
      const result = valuation(81n, 3n);
      expect(result.toString()).toBe(getExpected('valuation(81, 3)') ?? '4');
    });

    test('valuation(1000000, 2)', () => {
      const result = valuation(1000000n, 2n);
      expect(result.toString()).toBe(getExpected('valuation(1000000, 2)') ?? '6');
    });
  });

  // =============================================================================
  // next_prime Tests
  // =============================================================================
  describe('next_prime', () => {
    test('next_prime(10)', () => {
      const result = next_prime(10n);
      expect(result.toString()).toBe(getExpected('next_prime(10)') ?? '11');
    });

    test('next_prime(97)', () => {
      const result = next_prime(97n);
      expect(result.toString()).toBe(getExpected('next_prime(97)') ?? '101');
    });

    test('next_prime(1)', () => {
      const result = next_prime(1n);
      expect(result.toString()).toBe(getExpected('next_prime(1)') ?? '2');
    });

    test('next_prime(1000)', () => {
      const result = next_prime(1000n);
      expect(result.toString()).toBe(getExpected('next_prime(1000)') ?? '1009');
    });

    test('next_prime(2**20)', () => {
      const result = next_prime(2n ** 20n);
      expect(result.toString()).toBe(getExpected('next_prime(2**20)') ?? '1048583');
    });
  });

  // =============================================================================
  // previous_prime Tests
  // =============================================================================
  describe('previous_prime', () => {
    test('previous_prime(10)', () => {
      const result = previous_prime(10n);
      expect(result.toString()).toBe(getExpected('previous_prime(10)') ?? '7');
    });

    test('previous_prime(100)', () => {
      const result = previous_prime(100n);
      expect(result.toString()).toBe(getExpected('previous_prime(100)') ?? '97');
    });

    test('previous_prime(97)', () => {
      const result = previous_prime(97n);
      expect(result.toString()).toBe(getExpected('previous_prime(97)') ?? '89');
    });

    test('previous_prime(1000)', () => {
      const result = previous_prime(1000n);
      expect(result.toString()).toBe(getExpected('previous_prime(1000)') ?? '997');
    });

    test('previous_prime(3)', () => {
      const result = previous_prime(3n);
      expect(result.toString()).toBe(getExpected('previous_prime(3)') ?? '2');
    });
  });

  // =============================================================================
  // isqrt Tests
  // =============================================================================
  describe('isqrt', () => {
    test('isqrt(100)', () => {
      const result = isqrt(100n);
      expect(result.toString()).toBe(getExpected('isqrt(100)') ?? '10');
    });

    test('isqrt(99)', () => {
      const result = isqrt(99n);
      expect(result.toString()).toBe(getExpected('isqrt(99)') ?? '9');
    });

    test('isqrt(0)', () => {
      const result = isqrt(0n);
      expect(result.toString()).toBe(getExpected('isqrt(0)') ?? '0');
    });

    test('isqrt(1)', () => {
      const result = isqrt(1n);
      expect(result.toString()).toBe(getExpected('isqrt(1)') ?? '1');
    });

    test('isqrt(2**100)', () => {
      const result = isqrt(2n ** 100n);
      expect(result.toString()).toBe(
        getExpected('isqrt(2**100)') ?? (2n ** 50n).toString()
      );
    });
  });

  // =============================================================================
  // is_square Tests
  // =============================================================================
  describe('is_square', () => {
    test('is_square(100)', () => {
      const result = is_square(100n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_square(100)') ?? 'True'
      );
    });

    test('is_square(99)', () => {
      const result = is_square(99n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_square(99)') ?? 'False'
      );
    });

    test('is_square(0)', () => {
      const result = is_square(0n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_square(0)') ?? 'True'
      );
    });

    test('is_square(1)', () => {
      const result = is_square(1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_square(1)') ?? 'True'
      );
    });

    test('is_square(-1)', () => {
      const result = is_square(-1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_square(-1)') ?? 'False'
      );
    });

    test('is_square(2**100)', () => {
      const result = is_square(2n ** 100n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_square(2**100)') ?? 'True'
      );
    });
  });

  // =============================================================================
  // is_squarefree Tests
  // =============================================================================
  describe('is_squarefree', () => {
    test('is_squarefree(30)', () => {
      const result = is_squarefree(30n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_squarefree(30)') ?? 'True'
      );
    });

    test('is_squarefree(12)', () => {
      const result = is_squarefree(12n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_squarefree(12)') ?? 'False'
      );
    });

    test('is_squarefree(1)', () => {
      const result = is_squarefree(1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_squarefree(1)') ?? 'True'
      );
    });

    test('is_squarefree(97) - prime', () => {
      const result = is_squarefree(97n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_squarefree(97)') ?? 'True'
      );
    });

    test('is_squarefree(100)', () => {
      const result = is_squarefree(100n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_squarefree(100)') ?? 'False'
      );
    });
  });

  // =============================================================================
  // squarefree_part Tests
  // =============================================================================
  describe('squarefree_part', () => {
    test('squarefree_part(12)', () => {
      const result = squarefree_part(12n);
      expect(result.toString()).toBe(getExpected('squarefree_part(12)') ?? '3');
    });

    test('squarefree_part(72)', () => {
      const result = squarefree_part(72n);
      expect(result.toString()).toBe(getExpected('squarefree_part(72)') ?? '2');
    });

    test('squarefree_part(100)', () => {
      const result = squarefree_part(100n);
      expect(result.toString()).toBe(getExpected('squarefree_part(100)') ?? '1');
    });

    test('squarefree_part(30)', () => {
      const result = squarefree_part(30n);
      expect(result.toString()).toBe(getExpected('squarefree_part(30)') ?? '30');
    });

    test('squarefree_part(1)', () => {
      const result = squarefree_part(1n);
      expect(result.toString()).toBe(getExpected('squarefree_part(1)') ?? '1');
    });
  });

  // =============================================================================
  // prime_factors Tests
  // =============================================================================
  describe('prime_factors', () => {
    test('prime_divisors(12)', () => {
      const result = prime_factors(12n);
      expect(formatBigintArray(result)).toBe(getExpected('prime_divisors(12)') ?? '[2, 3]');
    });

    test('prime_divisors(100)', () => {
      const result = prime_factors(100n);
      expect(formatBigintArray(result)).toBe(getExpected('prime_divisors(100)') ?? '[2, 5]');
    });

    test('prime_divisors(1)', () => {
      const result = prime_factors(1n);
      expect(formatBigintArray(result)).toBe(getExpected('prime_divisors(1)') ?? '[]');
    });

    test('prime_divisors(97)', () => {
      const result = prime_factors(97n);
      expect(formatBigintArray(result)).toBe(getExpected('prime_divisors(97)') ?? '[97]');
    });

    test('prime_divisors(1001)', () => {
      const result = prime_factors(1001n);
      expect(formatBigintArray(result)).toBe(getExpected('prime_divisors(1001)') ?? '[7, 11, 13]');
    });
  });

  // =============================================================================
  // CRT Tests
  // =============================================================================
  describe('CRT', () => {
    test('CRT(2, 3, 3, 5)', () => {
      const result = crt(2n, 3n, 3n, 5n);
      expect(result.toString()).toBe(getExpected('CRT(2, 3, 3, 5)') ?? '8');
      // Verify: 8 mod 3 = 2, 8 mod 5 = 3
      expect(result % 3n).toBe(2n);
      expect(result % 5n).toBe(3n);
    });

    test('CRT(1, 2, 3, 7)', () => {
      const result = crt(1n, 2n, 3n, 7n);
      expect(result.toString()).toBe(getExpected('CRT(1, 2, 3, 7)') ?? '16');
      expect(result % 3n).toBe(1n);
      expect(result % 7n).toBe(2n);
    });

    test('CRT(0, 0, 5, 7)', () => {
      const result = crt(0n, 0n, 5n, 7n);
      expect(result.toString()).toBe(getExpected('CRT(0, 0, 5, 7)') ?? '0');
    });

    test('CRT_list([2, 3, 2], [3, 5, 7])', () => {
      const result = CRT_list([2n, 3n, 2n], [3n, 5n, 7n]);
      expect(result.toString()).toBe(getExpected('CRT_list([2, 3, 2], [3, 5, 7])') ?? '23');
      expect(result % 3n).toBe(2n);
      expect(result % 5n).toBe(3n);
      expect(result % 7n).toBe(2n);
    });
  });

  // =============================================================================
  // number_of_divisors Tests
  // =============================================================================
  describe('number_of_divisors', () => {
    test('number_of_divisors(12)', () => {
      const result = number_of_divisors(12n);
      expect(result.toString()).toBe(getExpected('number_of_divisors(12)') ?? '6');
    });

    test('number_of_divisors(100)', () => {
      const result = number_of_divisors(100n);
      expect(result.toString()).toBe(getExpected('number_of_divisors(100)') ?? '9');
    });

    test('number_of_divisors(1)', () => {
      const result = number_of_divisors(1n);
      expect(result.toString()).toBe(getExpected('number_of_divisors(1)') ?? '1');
    });

    test('number_of_divisors(97)', () => {
      const result = number_of_divisors(97n);
      expect(result.toString()).toBe(getExpected('number_of_divisors(97)') ?? '2');
    });
  });

  // =============================================================================
  // Large number tests
  // =============================================================================
  describe('Large number operations', () => {
    test('gcd(2**64, 2**32)', () => {
      const result = gcd(2n ** 64n, 2n ** 32n);
      expect(result.toString()).toBe(getExpected('gcd(2**64, 2**32)') ?? (2n ** 32n).toString());
    });

    test('is_prime(2**127-1) - Mersenne prime M127', () => {
      const result = is_prime(2n ** 127n - 1n);
      expect(result.toString().charAt(0).toUpperCase() + result.toString().slice(1)).toBe(
        getExpected('is_prime(2**127-1)') ?? 'True'
      );
    });

    test('euler_phi(2**32)', () => {
      const result = euler_phi(2n ** 32n);
      expect(result.toString()).toBe(getExpected('euler_phi(2**32)') ?? (2n ** 31n).toString());
    });

    test('next_prime(2**64)', () => {
      const result = next_prime(2n ** 64n);
      expect(result.toString()).toBe(getExpected('next_prime(2**64)') ?? '18446744073709551629');
    });
  });
});
