/**
 * Property tests for elliptic curve operations
 * Compares parigp-ts output with PARI/GP output
 *
 * This test file parses output from tests/property/pari/elliptic.gp
 * and verifies that our TypeScript implementation produces identical results.
 *
 * Usage:
 *   bun test tests/property/typescript/elliptic.test.ts
 *
 * Or via the comparison runner:
 *   bun run test:property:pari
 */

import { describe, test, expect, beforeAll } from 'bun:test';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

// Import from parigp-ts package
import {
  ellinit,
  ellcard,
  ellorder,
  ellgroup,
  elladd,
  ellsub,
  ellmul,
  ellneg,
  ellisoncurve,
  ellinit_Fp,
  ellpoint,
  ellinf,
  ell_is_inf,
  elllog,
  elldivpol,
  elltatepairing,
  ellweilpairing,
  FpE_add,
  FpE_neg,
  FpE_mul,
  type EllipticCurveFp,
  type EllipticPointFp,
} from '../../../packages/parigp-ts/src/index.js';

// Path to PARI output file (generated by run-comparison.sh)
const PARI_OUTPUT_PATH = join(
  import.meta.dir,
  '..',
  'transcripts',
  'pari',
  'elliptic.txt'
);

/**
 * Parsed PARI/GP test result
 */
interface PariTestResult {
  testNumber: number;
  operation: string;
  comments: string[];
  result: string;
}

/**
 * Parse PARI/GP output file into structured test results
 */
function parsePariOutput(content: string): PariTestResult[] {
  const results: PariTestResult[] = [];
  const lines = content.split('\n');

  let currentOperation = '';
  let currentComments: string[] = [];
  let testNumber = 0;

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith('# ') && !trimmed.match(/^# (P|Q|G|n |m |k |order|degree|card|e\(|dlog|-?\d|O$)/i)) {
      // This is an operation line (main description)
      currentOperation = trimmed.substring(2);
      currentComments = [];
    } else if (trimmed.startsWith('# ')) {
      // This is a comment/context line
      currentComments.push(trimmed.substring(2));
    } else if (trimmed.startsWith('RESULT: ')) {
      // This is a result line
      testNumber++;
      const result = trimmed.substring(8);
      results.push({
        testNumber,
        operation: currentOperation,
        comments: currentComments,
        result,
      });
      currentOperation = '';
      currentComments = [];
    }
  }

  return results;
}

/**
 * Parse a point string from PARI output
 * Format: "[x, y]" or "INFINITY"
 */
function parsePoint(s: string): EllipticPointFp {
  if (s === 'INFINITY') {
    return ellinf();
  }

  const match = s.match(/\[(-?\d+), (-?\d+)\]/);
  if (!match) {
    throw new Error(`Cannot parse point: ${s}`);
  }

  return ellpoint(BigInt(match[1]!), BigInt(match[2]!));
}

/**
 * Format a point to match PARI output
 */
function formatPoint(P: EllipticPointFp): string {
  if (ell_is_inf(P)) {
    return 'INFINITY';
  }
  return `[${P.x}, ${P.y}]`;
}

/**
 * Parse curve info from PARI output
 * Format: "a1=0, a2=0, a3=0, a4=1, a6=2, disc=..., j=..."
 */
interface CurveInfo {
  a1: bigint;
  a2: bigint;
  a3: bigint;
  a4: bigint;
  a6: bigint;
  disc: bigint;
  j: bigint;
}

function parseCurveInfo(s: string): CurveInfo {
  const parts = s.split(', ');
  const values: Record<string, bigint> = {};

  for (const part of parts) {
    const [key, value] = part.split('=');
    values[key!] = BigInt(value!);
  }

  return {
    a1: values['a1']!,
    a2: values['a2']!,
    a3: values['a3']!,
    a4: values['a4']!,
    a6: values['a6']!,
    disc: values['disc']!,
    j: values['j']!,
  };
}

/**
 * Format curve info to match PARI output
 */
function formatCurveInfo(E: ReturnType<typeof ellinit>): string {
  return `a1=${E.a1}, a2=${E.a2}, a3=${E.a3}, a4=${E.a4}, a6=${E.a6}, disc=${E.disc}, j=${E.j}`;
}

/**
 * Parse ellgroup result
 * Format: "[28]" or "[14, 2]" or "[]"
 */
function parseGroup(s: string): bigint[] {
  const match = s.match(/\[([^\]]*)\]/);
  if (!match) {
    throw new Error(`Cannot parse group: ${s}`);
  }

  if (match[1] === '') {
    return [];
  }

  return match[1]!.split(', ').map((x) => BigInt(x.trim()));
}

/**
 * Format group structure to match PARI output
 */
function formatGroup(group: bigint[]): string {
  return `[${group.join(', ')}]`;
}

/**
 * Parse polynomial from PARI output
 * Format: "[coeff0, coeff1, ..., coeffN]" (from lowest to highest degree)
 */
function parsePoly(s: string): bigint[] {
  if (s === '[]') return [];

  const match = s.match(/\[([^\]]*)\]/);
  if (!match) {
    throw new Error(`Cannot parse polynomial: ${s}`);
  }

  if (match[1] === '') {
    return [];
  }

  return match[1]!.split(', ').map((x) => BigInt(x.trim()));
}

/**
 * Format polynomial to match PARI output
 */
function formatPoly(coeffs: bigint[]): string {
  if (coeffs.length === 0) return '[]';
  return `[${coeffs.join(', ')}]`;
}

/**
 * Normalize polynomial by removing trailing zeros
 */
function normalizePoly(coeffs: bigint[]): bigint[] {
  let len = coeffs.length;
  while (len > 0 && coeffs[len - 1] === 0n) {
    len--;
  }
  return coeffs.slice(0, len);
}

/**
 * Wrapper functions to use the correct API from parigp-ts
 */
function FpE_add_wrapped(E: EllipticCurveFp, P: EllipticPointFp, Q: EllipticPointFp): EllipticPointFp {
  return FpE_add(P, Q, E.a4, E.p);
}

function FpE_neg_wrapped(E: EllipticCurveFp, P: EllipticPointFp): EllipticPointFp {
  return FpE_neg(P, E.p);
}

function FpE_mul_wrapped(E: EllipticCurveFp, P: EllipticPointFp, n: bigint): EllipticPointFp {
  return FpE_mul(P, n, E.a4, E.p);
}

// Store parsed PARI results
let pariResults: PariTestResult[] = [];
let pariOutputAvailable = false;

// Helper to find a result by test number
function getResult(testNum: number): PariTestResult | undefined {
  return pariResults.find(r => r.testNumber === testNum);
}

describe('Elliptic Curve Property Tests - PARI/GP Comparison', () => {
  beforeAll(() => {
    if (existsSync(PARI_OUTPUT_PATH)) {
      const content = readFileSync(PARI_OUTPUT_PATH, 'utf-8');
      pariResults = parsePariOutput(content);
      pariOutputAvailable = true;
      console.log(`Loaded ${pariResults.length} PARI test results`);
    } else {
      console.warn(
        '\n  PARI output not available. Run "bun run test:property:pari" to generate.\n'
      );
      console.warn(`  Expected path: ${PARI_OUTPUT_PATH}\n`);
    }
  });

  // ==========================================================================
  // SECTION 1: ellinit tests
  // ==========================================================================
  describe('ellinit tests', () => {
    test('Test 1: ellinit([1, 2], 101)', () => {
      const E = ellinit([1n, 2n], 101n);
      const tsResult = formatCurveInfo(E);

      const pari = getResult(1);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(E.a1).toBe(0n);
      expect(E.a2).toBe(0n);
      expect(E.a3).toBe(0n);
      expect(E.a4).toBe(1n);
      expect(E.a6).toBe(2n);
    });

    test('Test 2: ellinit([0, 0, 0, 1, 1], 23)', () => {
      const E = ellinit([0n, 0n, 0n, 1n, 1n], 23n);
      const tsResult = formatCurveInfo(E);

      const pari = getResult(2);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 3: ellinit([1, 2, 1, 3, 2], 37)', () => {
      const E = ellinit([1n, 2n, 1n, 3n, 2n], 37n);
      const tsResult = formatCurveInfo(E);

      const pari = getResult(3);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 2: ellcard tests
  // ==========================================================================
  describe('ellcard tests', () => {
    test('Test 4: ellcard for y^2 = x^3 + x + 1 over F_23', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(4);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 5: ellcard for y^2 = x^3 + 3x + 5 over F_101', () => {
      const E = ellinit_Fp(3n, 5n, 101n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(5);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 6: ellcard for y^2 = x^3 + 7 over F_97', () => {
      const E = ellinit_Fp(0n, 7n, 97n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(6);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 7: ellcard for y^2 = x^3 + 2x + 3 over F_997', () => {
      const E = ellinit_Fp(2n, 3n, 997n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(7);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 8: ellcard for y^2 = x^3 + 5x + 7 over F_509', () => {
      const E = ellinit_Fp(5n, 7n, 509n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(8);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 9: ellcard for y^2 = x^3 + x + 1 over F_1009', () => {
      const E = ellinit_Fp(1n, 1n, 1009n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(9);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 10: ellcard for j=0 curve y^2 = x^3 + 1 over F_67', () => {
      const E = ellinit_Fp(0n, 1n, 67n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(10);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 11: ellcard for j=1728 curve y^2 = x^3 + x over F_73', () => {
      const E = ellinit_Fp(1n, 0n, 73n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(11);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 3: Point operations
  // ==========================================================================
  describe('Point operations', () => {
    test('Test 12: elladd', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P1 = ellpoint(0n, 1n);
      const P2 = ellpoint(1n, 7n);
      const P3 = FpE_add_wrapped(E, P1, P2);
      const tsResult = formatPoint(P3);

      const pari = getResult(12);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 13: Point doubling', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const P_doubled = FpE_add_wrapped(E, P, P);
      const tsResult = formatPoint(P_doubled);

      const pari = getResult(13);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 14: Point negation', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const negP = FpE_neg_wrapped(E, P);
      const tsResult = formatPoint(negP);

      const pari = getResult(14);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 15: ellmul with n=5', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const nP = FpE_mul_wrapped(E, P, 5n);
      const tsResult = formatPoint(nP);

      const pari = getResult(15);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 16: ellmul with n=12', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const nP = FpE_mul_wrapped(E, P, 12n);
      const tsResult = formatPoint(nP);

      const pari = getResult(16);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 17: ellmul with n=-3', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const nP = FpE_mul_wrapped(E, P, -3n);
      const tsResult = formatPoint(nP);

      const pari = getResult(17);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 18: ellmul with large scalar n=1000', () => {
      const E = ellinit_Fp(3n, 5n, 101n);
      const P = ellpoint(1n, 3n);
      const result = FpE_mul_wrapped(E, P, 1000n);
      const tsResult = formatPoint(result);

      const pari = getResult(18);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 4: Point order tests
  // ==========================================================================
  describe('Point order tests', () => {
    test('Test 19: ellorder for P=[0, 1]', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const ord = ellorder(E, P);
      const tsResult = ord.toString();

      const pari = getResult(19);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 20: ellorder for P=[1, 7]', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(1n, 7n);
      const ord = ellorder(E, P);
      const tsResult = ord.toString();

      const pari = getResult(20);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 21: ellmul(P, order) = O', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const ord = ellorder(E, P);
      const nP = FpE_mul_wrapped(E, P, ord);
      const tsResult = formatPoint(nP);

      const pari = getResult(21);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(ell_is_inf(nP)).toBe(true);
    });
  });

  // ==========================================================================
  // SECTION 5: Identity element tests
  // ==========================================================================
  describe('Identity element tests', () => {
    test('Test 22: elladd(P, O) = P', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const O = ellinf();
      const result = FpE_add_wrapped(E, P, O);
      const tsResult = formatPoint(result);

      const pari = getResult(22);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 23: elladd(O, P) = P', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const O = ellinf();
      const result = FpE_add_wrapped(E, O, P);
      const tsResult = formatPoint(result);

      const pari = getResult(23);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 24: elladd(P, -P) = O', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const negP = FpE_neg_wrapped(E, P);
      const result = FpE_add_wrapped(E, P, negP);
      const tsResult = formatPoint(result);

      const pari = getResult(24);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(ell_is_inf(result)).toBe(true);
    });

    test('Test 25: ellmul with n=0', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const result = FpE_mul_wrapped(E, P, 0n);
      const tsResult = formatPoint(result);

      const pari = getResult(25);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(ell_is_inf(result)).toBe(true);
    });

    test('Test 26: ellmul with n=1', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const result = FpE_mul_wrapped(E, P, 1n);
      const tsResult = formatPoint(result);

      const pari = getResult(26);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 6: Discriminant and j-invariant tests
  // ==========================================================================
  describe('Discriminant and j-invariant', () => {
    test('Test 27: discriminant', () => {
      const E = ellinit([0n, 0n, 0n, 2n, 3n], 101n);
      const tsResult = E.disc.toString();

      const pari = getResult(27);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 28: j-invariant', () => {
      const E = ellinit([0n, 0n, 0n, 2n, 3n], 101n);
      const tsResult = E.j.toString();

      const pari = getResult(28);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 7: ellisoncurve tests
  // ==========================================================================
  describe('ellisoncurve tests', () => {
    test('Test 29: ellisoncurve for valid point', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const result = ellisoncurve(E, P);
      const tsResult = result ? '1' : '0';

      const pari = getResult(29);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(result).toBe(true);
    });

    test('Test 30: ellisoncurve for invalid point', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 5n);
      const result = ellisoncurve(E, P);
      const tsResult = result ? '1' : '0';

      const pari = getResult(30);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(result).toBe(false);
    });
  });

  // ==========================================================================
  // SECTION 8: ellgroup tests
  // ==========================================================================
  describe('ellgroup tests', () => {
    test('Test 31: ellgroup for E over F_23', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const grp = ellgroup(E);
      const tsResult = formatGroup(grp);

      const pari = getResult(31);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 32: ellgroup for E over F_101', () => {
      const E = ellinit_Fp(2n, 3n, 101n);
      const grp = ellgroup(E);
      const tsResult = formatGroup(grp);

      const pari = getResult(32);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 33: ellgroup for E over F_997', () => {
      const E = ellinit_Fp(5n, 7n, 997n);
      const grp = ellgroup(E);
      const tsResult = formatGroup(grp);

      const pari = getResult(33);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 9: Associativity and commutativity tests
  // ==========================================================================
  describe('Associativity tests', () => {
    test('Test 34: (P + Q) + R = P + (Q + R)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const Q = ellpoint(1n, 7n);

      const R = FpE_add_wrapped(E, P, Q);
      const S = FpE_add_wrapped(E, R, P);
      const T = FpE_add_wrapped(E, Q, P);
      const U = FpE_add_wrapped(E, P, T);

      const tsResult = formatPoint(U);

      const pari = getResult(34);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(formatPoint(S)).toBe(formatPoint(U));
    });

    test('Test 35: -3P = -(3P)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const neg3P = FpE_mul_wrapped(E, P, -3n);
      const pos3P = FpE_mul_wrapped(E, P, 3n);
      const neg_pos3P = FpE_neg_wrapped(E, pos3P);

      const tsResult = formatPoint(neg_pos3P);

      const pari = getResult(35);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(formatPoint(neg3P)).toBe(formatPoint(neg_pos3P));
    });
  });

  // ==========================================================================
  // SECTION 10: elllog tests
  // ==========================================================================
  describe('elllog tests', () => {
    test('Test 36: elllog basic', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const G = ellpoint(0n, 1n);
      const P = FpE_mul_wrapped(E, G, 5n);
      const dlog = elllog(E, P, G);
      const tsResult = dlog.toString();

      const pari = getResult(36);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 37: elllog for 12*G', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const G = ellpoint(0n, 1n);
      const P = FpE_mul_wrapped(E, G, 12n);
      const dlog = elllog(E, P, G);
      const tsResult = dlog.toString();

      const pari = getResult(37);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 38: elllog with order provided', () => {
      const E = ellinit_Fp(3n, 5n, 101n);
      const G = ellpoint(1n, 3n);
      const ordG = ellorder(E, G);
      const P = FpE_mul_wrapped(E, G, 17n);
      const dlog = elllog(E, P, G, ordG);
      const tsResult = dlog.toString();

      const pari = getResult(38);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 39: elllog for identity', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const G = ellpoint(0n, 1n);
      const P = ellinf();
      const dlog = elllog(E, P, G);
      const tsResult = dlog.toString();

      const pari = getResult(39);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(dlog).toBe(0n);
    });

    test('Test 73: elllog when P = G', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const G = ellpoint(0n, 1n);
      const dlog = elllog(E, G, G);
      const tsResult = dlog.toString();

      const pari = getResult(73);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(dlog).toBe(1n);
    });
  });

  // ==========================================================================
  // SECTION 11: elldivpol tests
  // ==========================================================================
  describe('elldivpol tests', () => {
    test('Test 41: elldivpol(E, 2)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const psi2 = elldivpol(E, 2);
      const tsResult = formatPoly(psi2);

      const pari = getResult(41);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 42: elldivpol(E, 3)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const psi3 = elldivpol(E, 3);
      const tsResult = formatPoly(psi3);

      const pari = getResult(42);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 43: elldivpol(E, 4)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const psi4 = elldivpol(E, 4);
      const tsResult = formatPoly(psi4);

      const pari = getResult(43);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 44: elldivpol(E, 5)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const psi5 = elldivpol(E, 5);
      const tsResult = formatPoly(psi5);

      const pari = getResult(44);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 45: elldivpol(E, 3) different curve', () => {
      const E = ellinit_Fp(2n, 3n, 101n);
      const psi3 = elldivpol(E, 3);
      const tsResult = formatPoly(psi3);

      const pari = getResult(45);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 46: elldivpol(E, 6)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const psi6 = elldivpol(E, 6);
      const tsResult = formatPoly(psi6);

      const pari = getResult(46);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 67: elldivpol degree check for n=5', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const psi5 = elldivpol(E, 5);
      // For odd n, degree should be (n^2-1)/2 = 12
      const expectedDegree = (5 * 5 - 1) / 2;
      const actualDegree = psi5.length - 1;

      const pari = getResult(67);
      if (pariOutputAvailable && pari) {
        expect(actualDegree.toString()).toBe(pari.result);
      }

      expect(actualDegree).toBe(expectedDegree);
    });
  });

  // ==========================================================================
  // SECTION 12: elltatepairing tests
  // ==========================================================================
  describe('elltatepairing tests', () => {
    test('Test 47: elltatepairing basic', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const Q = ellpoint(1n, 7n);
      const ordP = ellorder(E, P);
      const tate = elltatepairing(E, P, Q, ordP);
      const tsResult = tate.toString();

      const pari = getResult(47);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 48: elltatepairing(P, P)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const ordP = ellorder(E, P);
      const tate = elltatepairing(E, P, P, ordP);
      const tsResult = tate.toString();

      const pari = getResult(48);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 49: elltatepairing(O, Q)', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellinf();
      const Q = ellpoint(0n, 1n);
      const tate = elltatepairing(E, P, Q, 28n);
      const tsResult = tate.toString();

      const pari = getResult(49);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(tate).toBe(1n);
    });

    test('Test 50: elltatepairing on F_101', () => {
      const E = ellinit_Fp(2n, 3n, 101n);
      const P = ellpoint(73n, 35n);
      const Q = ellpoint(28n, 60n);
      const ordP = ellorder(E, P);
      const tate = elltatepairing(E, P, Q, ordP);
      const tsResult = tate.toString();

      const pari = getResult(50);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 13: ellweilpairing tests
  // ==========================================================================
  describe('ellweilpairing tests', () => {
    test('Test 51: ellweilpairing basic', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const Q = ellpoint(1n, 7n);

      const ordP = ellorder(E, P);
      const ordQ = ellorder(E, Q);
      const gcdOrd = gcd(ordP, ordQ);

      const weil = ellweilpairing(E, P, Q, gcdOrd);
      const tsResult = weil.toString();

      const pari = getResult(51);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 52: ellweilpairing symmetry', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const Q = ellpoint(1n, 7n);

      const ordP = ellorder(E, P);
      const ordQ = ellorder(E, Q);
      const ord = gcd(ordP, ordQ);

      const w1 = ellweilpairing(E, P, Q, ord);
      const w2 = ellweilpairing(E, Q, P, ord);
      const product = mod(w1 * w2, E.p);
      const tsResult = product.toString();

      const pari = getResult(52);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 53: ellweilpairing(P, P) = 1', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const ordP = ellorder(E, P);
      const weil = ellweilpairing(E, P, P, ordP);
      const tsResult = weil.toString();

      const pari = getResult(53);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      expect(weil).toBe(1n);
    });
  });

  // ==========================================================================
  // SECTION 14: Known curves tests
  // ==========================================================================
  describe('Known curves tests', () => {
    test('Test 54: secp256k1-like over F_2063', () => {
      const E = ellinit_Fp(0n, 7n, 2063n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(54);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 55: P-256-like over F_1997', () => {
      // a = -3 mod 1997 = 1994
      const E = ellinit_Fp(1994n, 5n, 1997n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(55);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 56: Curve y^2 = x^3 - 3x + 1 over F_127', () => {
      // -3 mod 127 = 124
      const E = ellinit_Fp(124n, 1n, 127n);
      const grp = ellgroup(E);
      const tsResult = formatGroup(grp);

      const pari = getResult(56);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 15: Random curve tests
  // ==========================================================================
  describe('Random curve tests', () => {
    test('Test 57: Random curve a4=17, a6=31 over F_229', () => {
      const E = ellinit_Fp(17n, 31n, 229n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(57);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 58: Random curve a4=42, a6=13 over F_307', () => {
      const E = ellinit_Fp(42n, 13n, 307n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(58);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 16: Edge cases
  // ==========================================================================
  describe('Edge cases', () => {
    test('Test 61: Very small prime p=5', () => {
      const E = ellinit_Fp(1n, 1n, 5n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(61);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 62: Prime p=7', () => {
      const E = ellinit_Fp(0n, 1n, 7n);  // y^2 = x^3 + 1 (non-singular)
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(62);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 63: Prime p=11', () => {
      const E = ellinit_Fp(3n, 4n, 11n);
      const grp = ellgroup(E);
      const tsResult = formatGroup(grp);

      const pari = getResult(63);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 64: Potential non-cyclic group over F_31', () => {
      const E = ellinit_Fp(1n, 0n, 31n);
      const grp = ellgroup(E);
      const tsResult = formatGroup(grp);

      const pari = getResult(64);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Singular curve should throw', () => {
      // 4*a4^3 + 27*a6^2 = 0 => singular
      // For a4=0, a6=0: disc = 0 (singular)
      expect(() => {
        ellinit_Fp(0n, 0n, 23n);
      }).toThrow();
    });

    test('Zero discriminant detection', () => {
      // disc = -4*a4^3 - 27*a6^2
      // For disc = 0 mod p, curve is singular
      // Find a4, a6 such that 4*a4^3 = -27*a6^2 mod p
      // For p=23: try a4=3, a6=2: 4*27 + 27*4 = 108 + 108 = 216 = 216 mod 23 = 216 - 9*23 = 216-207 = 9 != 0
      // Just verify a known singular case
      expect(() => {
        ellinit_Fp(0n, 0n, 23n);
      }).toThrow();
    });
  });

  // ==========================================================================
  // SECTION 17: Large field tests
  // ==========================================================================
  describe('Large field tests', () => {
    test('Test 71: ellcard for E over F_4999', () => {
      const E = ellinit_Fp(7n, 11n, 4999n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(71);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 18: Pairing bilinearity tests
  // ==========================================================================
  describe('Pairing bilinearity', () => {
    test('Test 68: elltatepairing bilinearity', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const Q = ellpoint(1n, 7n);
      const ordP = ellorder(E, P);

      const P2 = FpE_mul_wrapped(E, P, 2n);
      const tP2Q = elltatepairing(E, P2, Q, ordP);
      const tPQ = elltatepairing(E, P, Q, ordP);
      const tPQ2 = mod(tPQ * tPQ, E.p);

      // e(2P, Q) should equal e(P, Q)^2
      const tsResult = (tP2Q === tPQ2).toString().charAt(0).toUpperCase() + (tP2Q === tPQ2).toString().slice(1);

      const pari = getResult(68);
      if (pariOutputAvailable && pari) {
        expect(tsResult === 'True' ? '1' : '0').toBe(pari.result);
      }
    });

    test('Test 69: ellweilpairing bilinearity', () => {
      const E = ellinit_Fp(1n, 1n, 23n);
      const P = ellpoint(0n, 1n);
      const Q = ellpoint(1n, 7n);

      const ordP = ellorder(E, P);
      const ordQ = ellorder(E, Q);
      const ord = gcd(ordP, ordQ);

      const P2 = FpE_mul_wrapped(E, P, 2n);
      const wP2Q = ellweilpairing(E, P2, Q, ord);
      const wPQ = ellweilpairing(E, P, Q, ord);
      const wPQ2 = mod(wPQ * wPQ, E.p);

      const tsResult = (wP2Q === wPQ2).toString().charAt(0).toUpperCase() + (wP2Q === wPQ2).toString().slice(1);

      const pari = getResult(69);
      if (pariOutputAvailable && pari) {
        expect(tsResult === 'True' ? '1' : '0').toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 19: Verify elllog consistency
  // ==========================================================================
  describe('elllog consistency', () => {
    test('Test 70: elllog verification', () => {
      const E = ellinit_Fp(3n, 5n, 101n);
      const G = ellpoint(1n, 3n);
      const ordG = ellorder(E, G);
      const P = FpE_mul_wrapped(E, G, 37n);
      const dlog = elllog(E, P, G, ordG);
      const P_verify = FpE_mul_wrapped(E, G, dlog);

      const match = formatPoint(P) === formatPoint(P_verify);
      const tsResult = match.toString().charAt(0).toUpperCase() + match.toString().slice(1);

      const pari = getResult(70);
      if (pariOutputAvailable && pari) {
        expect(tsResult === 'True' ? '1' : '0').toBe(pari.result);
      }

      expect(match).toBe(true);
    });
  });

  // ==========================================================================
  // SECTION 23: Additional ellcard tests
  // ==========================================================================
  describe('Additional ellcard tests', () => {
    test('Test 76: ellcard for y^2 = x^3 + 1 over F_13', () => {
      const E = ellinit_Fp(0n, 1n, 13n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(76);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 77: ellcard over F_1021', () => {
      const E = ellinit_Fp(2n, 5n, 1021n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(77);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });

    test('Test 78: ellcard over F_257', () => {
      const E = ellinit_Fp(11n, 17n, 257n);
      const card = ellcard(E);
      const tsResult = card.toString();

      const pari = getResult(78);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }
    });
  });

  // ==========================================================================
  // SECTION 24: Additional elllog edge cases
  // ==========================================================================
  describe('Additional elllog edge cases', () => {
    test('Test 79: elllog with composite order', () => {
      const E = ellinit_Fp(3n, 5n, 101n);
      const G = ellpoint(1n, 3n);
      const ordG = ellorder(E, G);
      const k = ordG - 5n;
      const P = FpE_mul_wrapped(E, G, k);
      const dlog = elllog(E, P, G, ordG);
      const tsResult = dlog.toString();

      const pari = getResult(79);
      if (pariOutputAvailable && pari) {
        expect(tsResult).toBe(pari.result);
      }

      // Verify the result
      expect(dlog).toBe(k);
    });
  });

  // ==========================================================================
  // SECTION 25: Order verification
  // ==========================================================================
  describe('Order verification', () => {
    test('Test 80: ellmul(P, order(P)) = O', () => {
      const E = ellinit_Fp(5n, 7n, 127n);
      // Find a point on the curve
      let P: EllipticPointFp | null = null;
      for (let x = 1n; x <= 50n; x++) {
        const xMod = x % E.p;
        const y2 = mod(xMod * xMod * xMod + E.a4 * xMod + E.a6, E.p);
        const y = Fp_sqrt_simple(y2, E.p);
        if (y !== null) {
          P = ellpoint(xMod, y);
          break;
        }
      }

      if (P !== null) {
        const ord = ellorder(E, P);
        const Q = FpE_mul_wrapped(E, P, ord);
        const tsResult = formatPoint(Q);

        const pari = getResult(80);
        if (pariOutputAvailable && pari) {
          expect(tsResult).toBe(pari.result);
        }

        expect(ell_is_inf(Q)).toBe(true);
      }
    });
  });
});

// ==========================================================================
// Helper functions
// ==========================================================================

/**
 * Simple Tonelli-Shanks square root
 */
function Fp_sqrt_simple(a: bigint, p: bigint): bigint | null {
  a = mod(a, p);
  if (a === 0n) return 0n;

  // Check if a is a quadratic residue using Euler's criterion
  const exp = (p - 1n) / 2n;
  if (mod_pow(a, exp, p) !== 1n) {
    return null;
  }

  // Special case: p = 3 mod 4
  if (mod(p, 4n) === 3n) {
    return mod_pow(a, (p + 1n) / 4n, p);
  }

  // Tonelli-Shanks algorithm
  let s = 0n;
  let q = p - 1n;
  while ((q & 1n) === 0n) {
    s++;
    q >>= 1n;
  }

  let z = 2n;
  while (mod_pow(z, exp, p) !== p - 1n) {
    z++;
  }

  let m = s;
  let c = mod_pow(z, q, p);
  let t = mod_pow(a, q, p);
  let r = mod_pow(a, (q + 1n) / 2n, p);

  while (true) {
    if (t === 1n) return r;

    let i = 1n;
    let temp = mod(t * t, p);
    while (temp !== 1n) {
      temp = mod(temp * temp, p);
      i++;
    }

    const b = mod_pow(c, 1n << (m - i - 1n), p);
    m = i;
    c = mod(b * b, p);
    t = mod(t * c, p);
    r = mod(r * b, p);
  }
}

function mod_pow(base: bigint, exp: bigint, p: bigint): bigint {
  if (exp === 0n) return 1n;
  let result = 1n;
  base = mod(base, p);
  while (exp > 0n) {
    if ((exp & 1n) === 1n) {
      result = mod(result * base, p);
    }
    exp >>= 1n;
    base = mod(base * base, p);
  }
  return result;
}

function gcd(a: bigint, b: bigint): bigint {
  a = a < 0n ? -a : a;
  b = b < 0n ? -b : b;
  while (b !== 0n) {
    const t = b;
    b = a % b;
    a = t;
  }
  return a;
}

function mod(a: bigint, p: bigint): bigint {
  const r = a % p;
  return r < 0n ? r + p : r;
}
